// frontend-next-v1/app/component/admin/view/commun/client/list/client-list-admin.component.tsx
import {Button} from 'primereact/button';
import {Column} from 'primereact/column';


import {DataTable} from 'primereact/datatable';
import {Dialog} from 'primereact/dialog';
import {FileUpload} from 'primereact/fileupload';
import {InputText} from 'primereact/inputtext';
import {Toast} from 'primereact/toast';
import {Toolbar} from 'primereact/toolbar';
import React, {useEffect, useRef, useState} from 'react';
import {Paginator, PaginatorPageChangeEvent} from 'primereact/paginator';
import {Card} from 'primereact/card';
import {Calendar} from 'primereact/calendar';
import {InputNumber} from 'primereact/inputnumber';
import {Dropdown} from 'primereact/dropdown';
import {format} from "date-fns";
import useListHook from "app/component/zyhook/useListhook";
import {MessageService} from 'app/zynerator/service/MessageService';


import {ClientAdminService} from 'app/controller/service/admin/commun/ClientAdminService.service';
import {ClientDto}  from 'app/controller/model/commun/Client.model';
import {ClientCriteria} from 'app/controller/criteria/commun/ClientCriteria.model';


import { useTranslation } from 'react-i18next';

import Edit from '../edit/client-edit-admin.component';
import Create from '../create/client-create-admin.component';
import View from '../view/client-view-admin.component';


const List = () => {

    const { t } = useTranslation();

    const emptyItem = new ClientDto();
    const emptyCriteria = new ClientCriteria();
    const service = new ClientAdminService();


    const {
        items,
        showSearch,
        deleteItemDialog,
        item,
        selectedItems,
        setSelectedItems,
        hideDeleteItemDialog,
        globalFilter,
        setGlobalFilter,
        showCreateDialog,
        setShowCreateDialog,
        showEditDialog,
        setShowEditDialog,
        showViewDialog,
        setShowViewDialog,
        selectedItem,
        setSelectedItem,
        rows,
        totalRecords,
        criteria,
        setCriteria,
        first,
        fetchItems,
        toast,
        dt,
        findByCriteriaShow,
        handleCancelClick,
        confirmDeleteSelected,
        exportCSV,
        deleteItem,
        deleteItemDialogFooter,
        leftToolbarTemplate,
        rightToolbarTemplate,
        actionBodyTemplate,
        CustomBooleanCell,
        handleValidateClick,
        onPage,
        showCreateModal,
        showEditModal,
        showViewModal,
        add,
        update,
        confirmDeleteItem,
        statusBodyTemplate,
        formateDate,
        deleteSelectedItems,
        deleteItemsDialog,
        deleteItemsDialogFooter,
        hideDeleteItemsDialog
    } = useListHook<ClientDto, ClientCriteria>({ emptyItem, emptyCriteria,service, t})





    useEffect(() => {

        fetchItems(criteria);
    }, []);



    const header = (
    <div className="flex flex-column md:flex-row md:justify-content-between md:align-items-center">
        <h5 className="m-0">{t("client.header")}</h5>
        <span className="block mt-2 md:mt-0 p-input-icon-left"><i className="pi pi-search"/>
            <InputText type="search" onInput={(e) => setGlobalFilter(e.currentTarget.value)}
                       placeholder={t("search")}/> </span>
    </div>
    );
    return (
    <div className="grid crud-demo">
        <div className="col-12">
            <div className="card">
                <Toast ref={toast} />
                <Toolbar className="mb-4" left={leftToolbarTemplate} right={rightToolbarTemplate}></Toolbar>
                {findByCriteriaShow && (
                <Card title={t("search")} className="mb-5">
                        <div className="grid">
                            <div className="flex flex-column col-3">
                                <label className="mb-1"  htmlFor="1">{t("client.cin")}</label>
                                <InputText id="1" value={criteria.cin} onChange={(e) => setCriteria({ ...criteria, cin: e.target.value })} />
                            </div>
                            <div className="flex flex-column col-3">
                                <label className="mb-1"  htmlFor="2">{t("client.nom")}</label>
                                <InputText id="2" value={criteria.nom} onChange={(e) => setCriteria({ ...criteria, nom: e.target.value })} />
                            </div>
                            <div className="flex flex-column col-3">
                                <label className="mb-1"  htmlFor="3">{t("client.tel")}</label>
                                <InputText id="3" value={criteria.tel} onChange={(e) => setCriteria({ ...criteria, tel: e.target.value })} />
                            </div>
                            <div className="flex flex-column col-3">
                                <label className="mb-1"  htmlFor="4">{t("client.email")}</label>
                                <InputText id="4" value={criteria.email} onChange={(e) => setCriteria({ ...criteria, email: e.target.value })} />
                            </div>
                            <div className="flex flex-column col-3">
                                <label className="mb-1"  htmlFor="5">{t("client.adresse")}</label>
                                <InputText id="5" value={criteria.adresse} onChange={(e) => setCriteria({ ...criteria, adresse: e.target.value })} />
                            </div>
                            <div className="flex flex-column col-3">
                                <label className="mb-1"  htmlFor="6">{t("client.description")}</label>
                                <InputText id="6" value={criteria.description} onChange={(e) => setCriteria({ ...criteria, description: e.target.value })} />
                            </div>
                            <div className="flex flex-column col-3">
                                <label className="mb-1"  htmlFor="7-1">{t("client.creanceMin")}</label>
                                <InputNumber id="7-1" value={criteria.creanceMin} onChange={(e) => setCriteria({ ...criteria, creanceMin: e.value })} mode="decimal" />
                            </div>
                            <div className="flex flex-column col-3">
                                <label className="mb-1"  htmlFor="7-2">{t("client.creanceMax")}  </label>
                                <InputNumber id="7-2" value={criteria.creanceMax} onChange={(e) => setCriteria({ ...criteria, creanceMax: e.value })} mode="decimal" />
                            </div>
                        </div>
                        <div style={{ marginTop : '1rem', display: 'flex', justifyContent: 'flex-end' }} >
                            <Button label={t("validate")} icon="pi pi-sort-amount-down" className="p-button-info mr-2" onClick={handleValidateClick} />
                            <Button label={t("cancel")} className="p-button-secondary mr-2"  icon="pi pi-times" onClick={handleCancelClick} />
                        </div>
                </Card>
                )}
                <DataTable ref={dt} value={items} selection={selectedItems} onSelectionChange={(e) => setSelectedItems(e.value as ClientDto[])} dataKey="id" className="datatable-responsive" globalFilter={globalFilter} header={header} responsiveLayout="scroll" >
                    <Column selectionMode="multiple" headerStyle={{ width: '4rem' }}> </Column>
                    
                    <Column field="cin" header={t("client.cin")} sortable></Column>
                    
                    
                    <Column field="nom" header={t("client.nom")} sortable></Column>
                    
                    
                    <Column field="tel" header={t("client.tel")} sortable></Column>
                    
                    
                    <Column field="email" header={t("client.email")} sortable></Column>
                    
                    
                    <Column field="adresse" header={t("client.adresse")} sortable></Column>
                    
                    
                    <Column field="creance" header={t("client.creance")} sortable></Column>
                    
                    <Column header={t("actions")} body={actionBodyTemplate}></Column>
                </DataTable>
                <div className="p-d-flex p-ai-center p-jc-between">
                    <Paginator onPageChange={onPage} first={first} rows={rows} totalRecords={totalRecords} />
                </div>
                {showCreateDialog && <Create visible={showCreateDialog} onClose={() => setShowCreateDialog(false)} add={add} showToast={toast} list={items} service={service} t={t} />}

                {showEditDialog && <Edit  visible={showEditDialog} onClose={() =>  { setShowEditDialog(false); setSelectedItem(emptyItem); }} showToast={toast} selectedItem={selectedItem} update={update} list={items} service={service}   t={t} />}

                {showViewDialog && <View visible={showViewDialog} onClose={() =>  { setShowViewDialog(false); setSelectedItem(emptyItem); }} selectedItem={selectedItem}   t={t} />}
                <Dialog visible={deleteItemDialog} style={{width: '450px'}} header={t("confirm")} modal footer={deleteItemDialogFooter} onHide={hideDeleteItemDialog}>
                    <div className="flex align-items-center justify-content-center">
                    <i className="pi pi-exclamation-triangle mr-3" style={{fontSize: '2rem'}}/>
                    {item && (<span>{t("client.deleteClientConfirmationMessage")} <b>{item.nom}</b>?</span>)}
                    </div>
                </Dialog>

            <Dialog visible={deleteItemsDialog} style={{ width: '450px' }} header="Confirm" modal footer={deleteItemsDialogFooter} onHide={hideDeleteItemsDialog} >
                <div className="flex align-items-center justify-content-center">
                    <i className="pi pi-exclamation-triangle mr-3" style={{ fontSize: '2rem' }} />
                    {item && <span>{t("client.deleteClientsConfirmationMessage")}</span>}
                </div>
            </Dialog>

            </div>
        </div>
    </div>
);
};
export default List;

// frontend-angular/src/app/module/admin/view/commun/client/list/client-list-admin.component.ts
import {Component, OnInit} from '@angular/core';
import {ClientAdminService} from 'src/app/controller/service/admin/commun/ClientAdmin.service';
import {ClientDto} from 'src/app/controller/model/commun/Client.model';
import {ClientCriteria} from 'src/app/controller/criteria/commun/ClientCriteria.model';
import {AbstractListController} from 'src/app/zynerator/controller/AbstractListController';
import { environment } from 'src/environments/environment';



@Component({
  selector: 'app-client-list-admin',
  templateUrl: './client-list-admin.component.html'
})
export class ClientListAdminComponent extends AbstractListController<ClientDto, ClientCriteria, ClientAdminService>  implements OnInit {

    fileName = 'Client';



    constructor( private clientService: ClientAdminService  ) {
        super(clientService);
    }

    ngOnInit(): void {
        this.findPaginatedByCriteria();
        this.initExport();
        this.initCol();
    }


    public initCol() {
        this.cols = [
            {field: 'cin', header: 'Cin'},
            {field: 'nom', header: 'Nom'},
            {field: 'tel', header: 'Tel'},
            {field: 'email', header: 'Email'},
            {field: 'adresse', header: 'Adresse'},
            {field: 'creance', header: 'Creance'},
        ];
    }





   public prepareColumnExport(): void {
        this.exportData = this.items.map(e => {
            return {
                 'Cin': e.cin ,
                 'Nom': e.nom ,
                 'Email': e.email ,
                 'Description': e.description ,
                 'Creance': e.creance ,
            }
        });

        this.criteriaData = [{
            'Cin': this.criteria.cin ? this.criteria.cin : environment.emptyForExport ,
            'Nom': this.criteria.nom ? this.criteria.nom : environment.emptyForExport ,
            'Tel': this.criteria.tel ? this.criteria.tel : environment.emptyForExport ,
            'Email': this.criteria.email ? this.criteria.email : environment.emptyForExport ,
            'Adresse': this.criteria.adresse ? this.criteria.adresse : environment.emptyForExport ,
            'Description': this.criteria.description ? this.criteria.description : environment.emptyForExport ,
            'Creance Min': this.criteria.creanceMin ? this.criteria.creanceMin : environment.emptyForExport ,
            'Creance Max': this.criteria.creanceMax ? this.criteria.creanceMax : environment.emptyForExport ,
        }];
      }
}

<div class="grid">
    <div class="col-12">
        <p-toast></p-toast>
        <div class="card">
            <p-toolbar styleClass="mb-4">
                <ng-template pTemplate="left">
                                        <button pButton pRipple label=" {{'new' | translate}}" icon="pi pi-plus" class="p-button-success mr-2 mb-2" (click)="openCreate('Client')"></button>
                    <button [disabled]="isSelectionDisabled()" pButton pRipple label=" {{'delete' | translate}}" icon="pi pi-trash" class="p-button-danger mr-2 mb-2" (click)=deleteMultiple()></button>
                    <button pButton pRipple label=" {{'search' | translate}}" icon="pi pi-{{findByCriteriaShow?'angle-down':'angle-right'}}" class="p-button-warning mr-2 mb-2" (click)="this.showSearch()"></button>
                </ng-template>
                <ng-template pTemplate="right">
                    <div class="flex">
                        <p-splitButton label=" {{'export' | translate}}" icon="pi pi-download" styleClass="p-button-help" [model]="excelPdfButons"></p-splitButton>
                    </div>
                </ng-template>

            </p-toolbar>
            <p-toolbar *ngIf="findByCriteriaShow">

                <div class="col-12">
                    <div class="flex flex-wrap p-fluid col-12">
                       <div class="lg:col-3 md:col-6 sm:col-12 mb-4">
                            <label  class="font-bold block mb-2" for="1">{{'client.cin' | translate}}</label>
                            <input  class="w-full"  pInputText id="1" type="text"  [(ngModel)]="criteria.cinLike">
                        </div>
                       <div class="lg:col-3 md:col-6 sm:col-12 mb-4">
                            <label  class="font-bold block mb-2" for="2">{{'client.nom' | translate}}</label>
                            <input  class="w-full"  pInputText id="2" type="text"  [(ngModel)]="criteria.nomLike">
                        </div>
                       <div class="lg:col-3 md:col-6 sm:col-12 mb-4">
                            <label  class="font-bold block mb-2" for="4">{{'client.email' | translate}}</label>
                            <input  class="w-full"  pInputText id="4" type="text"  [(ngModel)]="criteria.emailLike">
                        </div>
                       <div class="lg:col-3 md:col-6 sm:col-12 mb-4">
                            <label  class="font-bold block mb-2" for="6">{{'client.description' | translate}}</label>
                            <input  class="w-full"  pInputText id="6" type="text"  [(ngModel)]="criteria.descriptionLike">
                        </div>
                        <div class="lg:col-3 md:col-6 sm:col-12 mb-4">
                            <label  class="font-bold block mb-2" for="7-1">{{'client.creanceMin' | translate}}</label>
                            <p-inputNumber  mode="decimal" [(ngModel)]="criteria.creanceMin" id="7-1"></p-inputNumber>
                        </div>
                        <div class="lg:col-3 md:col-6 sm:col-12 mb-4">
                            <label  class="font-bold block mb-2" for="7-2">{{'client.creanceMax' | translate}}</label>
                            <p-inputNumber  mode="decimal" [(ngModel)]="criteria.creanceMax" id="7-2"></p-inputNumber>
                       </div>
                    </div>
                    <div [style]="{ marginTop : '1rem', display: 'flex', justifyContent: 'flex-end' }">
                        <button pButton pRipple label="{{'validate' | translate}}" icon="pi pi-sort-amount-down" class="p-button-info mr-2" (click)="findPaginatedByCriteria()"></button>
                    </div>
                </div>


            </p-toolbar>


            <p-table #dt [value]="items" [columns]="cols" [rows]="8" [paginator]="false"
                    [globalFilterFields]="['cin', 'nom', 'tel', 'email', 'adresse', 'creance']" [(selection)]="selections"
                    [rowHover]="true" dataKey="id" styleClass="p-datatable-customers"
                    currentPageReportTemplate="{{'les éléments de {first} à {last} sur {totalRecords} ' | translate}}"
                    [showCurrentPageReport]="true" [rowsPerPageOptions]="[10,25,50]" selectionMode="multiple">
                <ng-template pTemplate="caption">
                    <div class="flex flex-column flex-row justify-content-between table-header">
                        <h5 class="p-m-0">{{'client.header' | translate}}</h5>
                        <span class="p-input-icon-left ml-auto">
                            <i class="pi pi-search"></i>
                            <input pInputText type="text" placeholder="{{'searchInput' | translate}}" (input)="dt.filterGlobal($event.target.value, 'contains')"/>
                        </span>
                    </div>
                </ng-template>
                <ng-template pTemplate="header">
                    <tr>
                        <th style="width: 3rem">
                            <p-tableHeaderCheckbox></p-tableHeaderCheckbox>
                        </th>
                                
                        <th pSortableColumn="cin">
                            <div class="p-d-flex p-jc-between p-ai-center">
                                <span>{{'client.cin' | translate}}</span>
                                <p-sortIcon field="cin"></p-sortIcon>
                                <p-columnFilter type="text" field="element.cin" display="menu" class="ml-auto"></p-columnFilter>
                            </div>
                        </th>
                                
                                
                        <th pSortableColumn="nom">
                            <div class="p-d-flex p-jc-between p-ai-center">
                                <span>{{'client.nom' | translate}}</span>
                                <p-sortIcon field="nom"></p-sortIcon>
                                <p-columnFilter type="text" field="element.nom" display="menu" class="ml-auto"></p-columnFilter>
                            </div>
                        </th>
                                
                                
                        <th pSortableColumn="tel">
                            <div class="p-d-flex p-jc-between p-ai-center">
                                <span>{{'client.tel' | translate}}</span>
                                <p-sortIcon field="tel"></p-sortIcon>
                            </div>
                        </th>
                                
                                
                        <th pSortableColumn="email">
                            <div class="p-d-flex p-jc-between p-ai-center">
                                <span>{{'client.email' | translate}}</span>
                                <p-sortIcon field="email"></p-sortIcon>
                                <p-columnFilter type="text" field="element.email" display="menu" class="ml-auto"></p-columnFilter>
                            </div>
                        </th>
                                
                                
                        <th pSortableColumn="adresse">
                            <div class="p-d-flex p-jc-between p-ai-center">
                                <span>{{'client.adresse' | translate}}</span>
                                <p-sortIcon field="adresse"></p-sortIcon>
                            </div>
                        </th>
                                
                                
                        <th pSortableColumn="creance">
                            <div class="p-d-flex p-jc-between p-ai-center">
                                <span>{{'client.creance' | translate}}</span>
                                <p-sortIcon field="creance"></p-sortIcon>
                            </div>
                        </th>
                                
                        <th>Actions</th>
                    </tr>
                </ng-template>
                <ng-template pTemplate="body" let-element>
                    <tr>
                        <td>
                            <p-tableCheckbox [value]="element"></p-tableCheckbox>
                        </td>
                            
                        <td>{{element.cin}}</td>
                            
                            
                        <td>{{element.nom}}</td>
                            
                            
                        <td>{{element.tel}}</td>
                            
                            
                        <td>{{element.email}}</td>
                            
                            
                        <td>{{element.adresse}}</td>
                            
                            
                        <td>{{element.creance}}</td>
                            
                        <td>
                            <button pButton pRipple icon="pi pi-pencil"  class="p-button-rounded p-button-success mr-2" (click)="edit(element)"></button>
                            <button pButton pRipple icon="pi pi-list" class="p-button-rounded p-button-info mr-2" (click)="view(element)"></button>
                            <button pButton pRipple icon="pi pi-trash" class="p-button-rounded p-button-danger mr-2" (click)="delete(element)"></button>
                            <button pButton pRipple icon="pi pi-copy" class="p-button-rounded p-button-raised p-button-warning mr-2" (click)="duplicate(element)"></button>
                        </td>
                    </tr>
                </ng-template>

                <ng-template pTemplate="summary">
                    <p-paginator  [rows]="10" [totalRecords]="totalRecords" (onPageChange)="onPage($event)"></p-paginator>
                    <div class="p-d-flex p-ai-center p-jc-between">
                        En totale il {{items ? totalRecords == 1 ? 'y a' : 'y a' : 'y a' }} {{items ? totalRecords : 0 }} {{items ? totalRecords == 1 ? 'client' : 'clients' : 0 }}.
                    </div>
                </ng-template>
            </p-table>
        </div>

        <app-client-create-admin  *ngIf="createDialog"></app-client-create-admin>
        <app-client-edit-admin  *ngIf="editDialog"></app-client-edit-admin>
        <app-client-view-admin  *ngIf="viewDialog"></app-client-view-admin>
        <p-confirmDialog [style]="{width: '450px'}"></p-confirmDialog>
    </div>
</div>
