// frontend-angular/src/app/module/admin/view/stock/achat/view/achat-view-admin.component.ts
import {Component, OnInit} from '@angular/core';


import {AbstractViewController} from 'src/app/zynerator/controller/AbstractViewController';
import { environment } from 'src/environments/environment';

import {AchatAdminService} from 'src/app/controller/service/admin/stock/AchatAdmin.service';
import {AchatDto} from 'src/app/controller/model/stock/Achat.model';
import {AchatCriteria} from 'src/app/controller/criteria/stock/AchatCriteria.model';

import {ProduitDto} from 'src/app/controller/model/commun/Produit.model';
import {ProduitAdminService} from 'src/app/controller/service/admin/commun/ProduitAdmin.service';
import {AchatItemDto} from 'src/app/controller/model/stock/AchatItem.model';
import {AchatItemAdminService} from 'src/app/controller/service/admin/stock/AchatItemAdmin.service';
import {ClientDto} from 'src/app/controller/model/commun/Client.model';
import {ClientAdminService} from 'src/app/controller/service/admin/commun/ClientAdmin.service';
@Component({
  selector: 'app-achat-view-admin',
  templateUrl: './achat-view-admin.component.html'
})
export class AchatViewAdminComponent extends AbstractViewController<AchatDto, AchatCriteria, AchatAdminService> implements OnInit {

    achatItems = new AchatItemDto();
    achatItemss: Array<AchatItemDto> = [];

    constructor(private achatService: AchatAdminService, private produitService: ProduitAdminService, private achatItemService: AchatItemAdminService, private clientService: ClientAdminService){
        super(achatService);
    }

    ngOnInit(): void {
    }


    get produit(): ProduitDto {
       return this.produitService.item;
    }
    set produit(value: ProduitDto) {
        this.produitService.item = value;
    }
    get produits(): Array<ProduitDto> {
       return this.produitService.items;
    }
    set produits(value: Array<ProduitDto>) {
        this.produitService.items = value;
    }
    get client(): ClientDto {
       return this.clientService.item;
    }
    set client(value: ClientDto) {
        this.clientService.item = value;
    }
    get clients(): Array<ClientDto> {
       return this.clientService.items;
    }
    set clients(value: Array<ClientDto>) {
        this.clientService.items = value;
    }


}


<p-dialog [(visible)]="viewDialog" [style]="{width: '70vw'}" header="{{'achat.tabPan' | translate}}" [modal]="true" styleClass="p-fluid">
    <ng-template pTemplate="content">
        <p-tabView>
            <p-tabPanel header="{{'achat.tabPan' | translate}}">
                <div class="grid">
                    <div class="field col-12 md:col-6">
                        <label for="1">{{'achat.reference' | translate}}</label>
                        <input class="mb-2 mr-2" type="text" pInputText [disabled]="true" placeholder="{{'achat.reference' | translate}}" autofocus  id="1" [(ngModel)]="item.reference">
                    </div>
                    <div class="field col-12 md:col-6">
                        <label for="2">{{'achat.dateAchat' | translate}}</label>
                        <p-calendar id="2" [disabled]="true"  [showTime]="true" [showSeconds]="false" placeholder="{{'achat.dateAchat' | translate}}"  [(ngModel)]="item.dateAchat" dateFormat="{{dateFormat}}"></p-calendar>
                    </div>
                    <div class="field col-12 md:col-6">
                        <label for="3">{{'achat.total' | translate}}</label>
                        <p-inputNumber class="mb-2 mr-2" id="3" [disabled]="true" placeholder="{{'achat.total' | translate}}" [(ngModel)]="item.total"></p-inputNumber>
                    </div>
                    <div class="field col-12 md:col-6">
                        <label for="4">{{'achat.totalPaye' | translate}}</label>
                        <p-inputNumber class="mb-2 mr-2" id="4" [disabled]="true" placeholder="{{'achat.totalPaye' | translate}}" [(ngModel)]="item.totalPaye"></p-inputNumber>
                    </div>
                    <div class="field col-12 md:col-6">
                        <label for="5">{{'achat.description' | translate}}</label>
                        <textarea id="5" pInputTextarea rows="5" cols="30" [disabled]="true" placeholder="{{'achat.description' | translate}}"  [(ngModel)]="item.description"></textarea>
                    </div>
                    <div class="field col-12 md:col-6">
                        <label for="6">{{'achat.client' | translate}}</label>
                        <input class="mb-2 mr-2" type="text" pInputText [disabled]="true" placeholder="{{'achat.client' | translate}}" autofocus  id="6" [(ngModel)]="item.client.nom">
                    </div>
                </div>
            </p-tabPanel>

            <p-tabPanel header="{{'achat.achatItems' | translate}}">
                <div class="grid">
                    <div class="col">
                        <div class="card">
                            <p-table [value]="item.achatItems" [scrollable]="true" scrollHeight="200px">
                                <ng-template pTemplate="header">
                                    <tr>
                                        <th>Produit</th>
                                        <th>Prix unitaire</th>
                                        <th>Prix vente</th>
                                        <th>Quantite</th>
                                        <th>Quantite avoir</th>
                                        <th>Remise</th>
                                    </tr>
                                </ng-template>
                                <ng-template pTemplate="body" let-p>
                                    <tr>
                                        <td>{{p.produit.reference}}</td>
                                        <td>{{p.prixUnitaire}}</td>
                                        <td>{{p.prixVente}}</td>
                                        <td>{{p.quantite}}</td>
                                        <td>{{p.quantiteAvoir}}</td>
                                        <td>{{p.remise}}</td>
                                    </tr>
                                </ng-template>
                            </p-table>
                        </div>
                    </div>
                </div>
            </p-tabPanel>
        </p-tabView>

    </ng-template>

    <ng-template pTemplate="footer" >
        <div class="grid-footer">
            <div>
                <button pButton pRipple label="Annuler" icon="pi pi-times" class="p-button-outlined" (click)="hideViewDialog()"></button>
            </div>
        </div>
    </ng-template>
</p-dialog>

// error-ng-build-list-hook/frontend-react-v2/app/component/admin/view/stock/achat/view/achat-view-admin.component.tsx
import {Column} from 'primereact/column';
import {TabPanel, TabView} from 'primereact/tabview';
import {DataTable} from 'primereact/datatable';
import {Dialog} from 'primereact/dialog';
import {InputNumber} from 'primereact/inputnumber';
import {InputText} from 'primereact/inputtext';
import {InputTextarea} from 'primereact/inputtextarea';
import React from 'react';
import {Calendar} from 'primereact/calendar';
import {InputSwitch} from 'primereact/inputswitch';
import {TFunction} from "i18next";
import useViewHook from "app/component/zyhook/useViewhook";

import  {AchatDto}  from 'app/controller/model/stock/Achat.model';

type AchatViewAdminType = {
    visible: boolean,
    onClose: () => void,
    selectedItem: AchatDto,
    t: TFunction
}

const View: React.FC<AchatViewAdminType> = ({visible,onClose,selectedItem, t}) => {

    const {
    onTabChange,
    hideDialog,
    itemDialogFooter,
    formateDate,
    parse,
    parseToIsoFormat,
    adaptDate,
    activeIndex
    } = useViewHook<AchatDto>({selectedItem, onClose})

        return(
<Dialog visible={visible} style={{width: '70vw'}} header={t("achat.tabPan")} modal className="p-fluid" footer={itemDialogFooter} onHide={hideDialog} >
<TabView activeIndex={activeIndex} onTabChange={onTabChange}>
<TabPanel header={t("achat.tabPan")}>
    <div className="formgrid grid">

            <div className="field col-6">
                <label htmlFor="reference">{t("achat.reference")}</label>
                <InputText id="reference" value={selectedItem?.reference} disabled   />
            </div>

        <div className="field col-6">
            <label htmlFor="dateAchat">{t("achat.dateAchat")}</label>
            <Calendar id="dateAchat" value={adaptDate(selectedItem?.dateAchat)} disabled dateFormat="dd/mm/yy" showIcon={true}  />
        </div>

                <div className="field col-6">
                    <label htmlFor="total">{t("achat.total")}</label>
                    <InputNumber id="total" value={selectedItem.total} disabled/>
                </div>

                <div className="field col-6">
                    <label htmlFor="totalPaye">{t("achat.totalPaye")}</label>
                    <InputNumber id="totalPaye" value={selectedItem.totalPaye} disabled/>
                </div>

            <div className="field col-6">
                <label htmlFor="description">{t("achat.description")}</label>
                <span className="p-float-label">
                   <InputTextarea id="description" value={selectedItem?.description} disabled rows={5} cols={30} />
                </span>
            </div>

                <div className="field col-6">
                    <label htmlFor="client">{t("achat.client")}</label>
                    <InputText  id="clientDropdown"  value={selectedItem?.client?.nom}  disabled  />
                </div>
        </div>
</TabPanel>
    <TabPanel header={t("achat.achatItems")}>
                <div className="card">
                    <DataTable value={selectedItem?.achatItems} tableStyle={{minWidth: '50rem'}} dataKey="id">
                                <Column field="produit.reference" header={t("achatItem.produit")}></Column>
                                <Column field="prixUnitaire" header={t("achatItem.prixUnitaire")}   ></Column>
                                <Column field="prixVente" header={t("achatItem.prixVente")}   ></Column>
                                <Column field="quantite" header={t("achatItem.quantite")}   ></Column>
                                <Column field="quantiteAvoir" header={t("achatItem.quantiteAvoir")}   ></Column>
                                <Column field="remise" header={t("achatItem.remise")}   ></Column>
                    </DataTable>
                </div>
        </TabPanel>
</TabView>
</Dialog>
);
};
export default View;
