// frontend-next-v1/components/admin/view/commun/client/view/client-view-admin.component.tsx
import {Column} from 'primereact/column';
import {TabPanel, TabView} from 'primereact/tabview';
import {DataTable} from 'primereact/datatable';
import {Dialog} from 'primereact/dialog';
import {InputNumber} from 'primereact/inputnumber';
import {InputText} from 'primereact/inputtext';
import {InputTextarea} from 'primereact/inputtextarea';
import React from 'react';
import {Calendar} from 'primereact/calendar';
import {InputSwitch} from 'primereact/inputswitch';
import {TFunction} from "i18next";

import  {ClientDto}  from '@/controller/model/commun/Client.model';

import useViewHook from "@/utils/zyhook/useViewhook";

type ClientViewAdminType = {
    visible: boolean,
    onClose: () => void,
    selectedItem: ClientDto,
    t: TFunction
}

const View: React.FC<ClientViewAdminType> = ({visible,onClose,selectedItem, t}) => {

    const {
    onTabChange,
    hideDialog,
    itemDialogFooter,
    formateDate,
    parse,
    parseToIsoFormat,
    adaptDate,
    activeIndex
    } = useViewHook<ClientDto>({selectedItem, onClose})

        return(
<Dialog visible={visible} style={{width: '70vw'}} header={t("client.tabPan")} modal className="p-fluid" footer={itemDialogFooter} onHide={hideDialog} >
<TabView activeIndex={activeIndex} onTabChange={onTabChange}>
<TabPanel header={t("client.tabPan")}>
    <div className="formgrid grid">

            <div className="field col-6">
                <label htmlFor="cin">{t("client.cin")}</label>
                <InputText id="cin" value={selectedItem?.cin} disabled   />
            </div>

            <div className="field col-6">
                <label htmlFor="nom">{t("client.nom")}</label>
                <InputText id="nom" value={selectedItem?.nom} disabled   />
            </div>

            <div className="field col-6">
                <label htmlFor="tel">{t("client.tel")}</label>
                <InputText id="tel" value={selectedItem?.tel} disabled   />
            </div>

            <div className="field col-6">
                <label htmlFor="email">{t("client.email")}</label>
                <InputText id="email" value={selectedItem?.email} disabled   />
            </div>

            <div className="field col-6">
                <label htmlFor="adresse">{t("client.adresse")}</label>
                <InputText id="adresse" value={selectedItem?.adresse} disabled   />
            </div>

            <div className="field col-6">
                <label htmlFor="description">{t("client.description")}</label>
                <span className="p-float-label">
                   <InputTextarea id="description" value={selectedItem?.description} disabled rows={5} cols={30} />
                </span>
            </div>

                <div className="field col-6">
                    <label htmlFor="creance">{t("client.creance")}</label>
                    <InputNumber id="creance" value={selectedItem.creance} disabled/>
                </div>

        </div>
</TabPanel>
</TabView>
</Dialog>
);
};
export default View;

// frontend-angular/src/app/module/admin/view/commun/client/view/client-view-admin.component.ts
import {Component, OnInit} from '@angular/core';


import {AbstractViewController} from 'src/app/zynerator/controller/AbstractViewController';
import { environment } from 'src/environments/environment';

import {ClientAdminService} from 'src/app/controller/service/admin/commun/ClientAdmin.service';
import {ClientDto} from 'src/app/controller/model/commun/Client.model';
import {ClientCriteria} from 'src/app/controller/criteria/commun/ClientCriteria.model';

@Component({
  selector: 'app-client-view-admin',
  templateUrl: './client-view-admin.component.html'
})
export class ClientViewAdminComponent extends AbstractViewController<ClientDto, ClientCriteria, ClientAdminService> implements OnInit {


    constructor(private clientService: ClientAdminService){
        super(clientService);
    }

    ngOnInit(): void {
    }




}


<p-dialog [(visible)]="viewDialog" [style]="{width: '70vw'}" header="{{'client.tabPan' | translate}}" [modal]="true" styleClass="p-fluid">
    <ng-template pTemplate="content">
        <p-tabView>
            <p-tabPanel header="{{'client.tabPan' | translate}}">
                <div class="grid">
                    <div class="field col-12 md:col-6">
                        <label for="1">{{'client.cin' | translate}}</label>
                        <input class="mb-2 mr-2" type="text" pInputText [disabled]="true" placeholder="{{'client.cin' | translate}}" autofocus  id="1" [(ngModel)]="item.cin">
                    </div>
                    <div class="field col-12 md:col-6">
                        <label for="2">{{'client.nom' | translate}}</label>
                        <input class="mb-2 mr-2" type="text" pInputText [disabled]="true" placeholder="{{'client.nom' | translate}}" autofocus  id="2" [(ngModel)]="item.nom">
                    </div>
                    <div class="field col-12 md:col-6">
                        <label for="3">{{'client.tel' | translate}}</label>
                        <p-inputNumber class="mb-2 mr-2" id="3" [disabled]="true" placeholder="{{'client.tel' | translate}}" [(ngModel)]="item.tel"></p-inputNumber>
                    </div>
                    <div class="field col-12 md:col-6">
                        <label for="4">{{'client.email' | translate}}</label>
                        <input class="mb-2 mr-2" type="text" pInputText [disabled]="true" placeholder="{{'client.email' | translate}}" autofocus  id="4" [(ngModel)]="item.email">
                    </div>
                    <div class="field col-12 md:col-6">
                        <label for="5">{{'client.adresse' | translate}}</label>
                        <p-inputNumber class="mb-2 mr-2" id="5" [disabled]="true" placeholder="{{'client.adresse' | translate}}" [(ngModel)]="item.adresse"></p-inputNumber>
                    </div>
                    <div class="field col-12 md:col-6">
                        <label for="6">{{'client.description' | translate}}</label>
                        <textarea id="6" pInputTextarea rows="5" cols="30" [disabled]="true" placeholder="{{'client.description' | translate}}"  [(ngModel)]="item.description"></textarea>
                    </div>
                    <div class="field col-12 md:col-6">
                        <label for="7">{{'client.creance' | translate}}</label>
                        <p-inputNumber class="mb-2 mr-2" id="7" [disabled]="true" placeholder="{{'client.creance' | translate}}" [(ngModel)]="item.creance"></p-inputNumber>
                    </div>
                </div>
            </p-tabPanel>

        </p-tabView>

    </ng-template>

    <ng-template pTemplate="footer" >
        <div class="grid-footer">
            <div>
                <button pButton pRipple label="Annuler" icon="pi pi-times" class="p-button-outlined" (click)="hideViewDialog()"></button>
            </div>
        </div>
    </ng-template>
</p-dialog>
