// frontend-angular/src/app/module/admin/view/stock/achat-item/list/achat-item-list-admin.component.ts
import {Component, OnInit} from '@angular/core';
import {AchatItemAdminService} from 'src/app/controller/service/admin/stock/AchatItemAdmin.service';
import {AchatItemDto} from 'src/app/controller/model/stock/AchatItem.model';
import {AchatItemCriteria} from 'src/app/controller/criteria/stock/AchatItemCriteria.model';
import {AbstractListController} from 'src/app/zynerator/controller/AbstractListController';
import { environment } from 'src/environments/environment';

import {ProduitDto} from 'src/app/controller/model/commun/Produit.model';
import {ProduitAdminService} from 'src/app/controller/service/admin/commun/ProduitAdmin.service';
import {AchatDto} from 'src/app/controller/model/stock/Achat.model';
import {AchatAdminService} from 'src/app/controller/service/admin/stock/AchatAdmin.service';


@Component({
  selector: 'app-achat-item-list-admin',
  templateUrl: './achat-item-list-admin.component.html'
})
export class AchatItemListAdminComponent extends AbstractListController<AchatItemDto, AchatItemCriteria, AchatItemAdminService>  implements OnInit {

    fileName = 'AchatItem';

    produits: Array<ProduitDto>;
    achats: Array<AchatDto>;


    constructor( private achatItemService: AchatItemAdminService  , private produitService: ProduitAdminService, private achatService: AchatAdminService) {
        super(achatItemService);
    }

    ngOnInit(): void {
        this.findPaginatedByCriteria();
        this.initExport();
        this.initCol();
        this.loadProduit();
        this.loadAchat();
    }


    public initCol() {
        this.cols = [
            {field: 'produit?.reference', header: 'Produit'},
            {field: 'prixUnitaire', header: 'Prix unitaire'},
            {field: 'prixVente', header: 'Prix vente'},
            {field: 'quantite', header: 'Quantite'},
            {field: 'quantiteAvoir', header: 'Quantite avoir'},
            {field: 'remise', header: 'Remise'},
            {field: 'achat?.reference', header: 'Achat'},
        ];
    }


    public async loadProduit(){
       this.produitService.findAllOptimized().subscribe(produits => this.produits = produits, error => console.log(error))
    }
    public async loadAchat(){
       this.achatService.findAllOptimized().subscribe(achats => this.achats = achats, error => console.log(error))
    }



   public prepareColumnExport(): void {
        this.exportData = this.items.map(e => {
            return {
                'Produit': e.produit?.reference ,
                 'Prix unitaire': e.prixUnitaire ,
                 'Prix vente': e.prixVente ,
                 'Quantite': e.quantite ,
                 'Quantite avoir': e.quantiteAvoir ,
                 'Remise': e.remise ,
                'Achat': e.achat?.reference ,
            }
        });

        this.criteriaData = [{
        //'Produit': this.criteria.produit?.reference ? this.criteria.produit?.reference : environment.emptyForExport ,
            'Prix unitaire Min': this.criteria.prixUnitaireMin ? this.criteria.prixUnitaireMin : environment.emptyForExport ,
            'Prix unitaire Max': this.criteria.prixUnitaireMax ? this.criteria.prixUnitaireMax : environment.emptyForExport ,
            'Prix vente Min': this.criteria.prixVenteMin ? this.criteria.prixVenteMin : environment.emptyForExport ,
            'Prix vente Max': this.criteria.prixVenteMax ? this.criteria.prixVenteMax : environment.emptyForExport ,
            'Quantite Min': this.criteria.quantiteMin ? this.criteria.quantiteMin : environment.emptyForExport ,
            'Quantite Max': this.criteria.quantiteMax ? this.criteria.quantiteMax : environment.emptyForExport ,
            'Quantite avoir Min': this.criteria.quantiteAvoirMin ? this.criteria.quantiteAvoirMin : environment.emptyForExport ,
            'Quantite avoir Max': this.criteria.quantiteAvoirMax ? this.criteria.quantiteAvoirMax : environment.emptyForExport ,
            'Remise Min': this.criteria.remiseMin ? this.criteria.remiseMin : environment.emptyForExport ,
            'Remise Max': this.criteria.remiseMax ? this.criteria.remiseMax : environment.emptyForExport ,
        //'Achat': this.criteria.achat?.reference ? this.criteria.achat?.reference : environment.emptyForExport ,
        }];
      }
}

<div class="grid">
    <div class="col-12">
        <p-toast></p-toast>
        <div class="card">
            <p-toolbar styleClass="mb-4">
                <ng-template pTemplate="left">
                                        <button pButton pRipple label=" {{'new' | translate}}" icon="pi pi-plus" class="p-button-success mr-2 mb-2" (click)="openCreate('AchatItem')"></button>
                    <button [disabled]="isSelectionDisabled()" pButton pRipple label=" {{'delete' | translate}}" icon="pi pi-trash" class="p-button-danger mr-2 mb-2" (click)=deleteMultiple()></button>
                    <button pButton pRipple label=" {{'search' | translate}}" icon="pi pi-{{findByCriteriaShow?'angle-down':'angle-right'}}" class="p-button-warning mr-2 mb-2" (click)="this.showSearch()"></button>
                </ng-template>
                <ng-template pTemplate="right">
                    <div class="flex">
                        <p-splitButton label=" {{'export' | translate}}" icon="pi pi-download" styleClass="p-button-help" [model]="excelPdfButons"></p-splitButton>
                    </div>
                </ng-template>

            </p-toolbar>
            <p-toolbar *ngIf="findByCriteriaShow">

                <div class="col-12">
                    <div class="flex flex-wrap p-fluid col-12">
                        <div class="lg:col-3 md:col-6 sm:col-12 mb-4">
                            <label  class="font-bold block mb-2" for="1-2">{{'achatItem.produit' | translate}} Max</label>
                            <p-dropdown [options]="produits" [(ngModel)]="criteria.produit" id="1" [filter]="true" class="p-fluid"
                                        [showClear]="true"  placeholder="{{'achatItem.produit' | translate}}" optionLabel="reference">
                            </p-dropdown>
                        </div>
                        <div class="lg:col-3 md:col-6 sm:col-12 mb-4">
                            <label  class="font-bold block mb-2" for="2-1">{{'achatItem.prixUnitaireMin' | translate}}</label>
                            <p-inputNumber  mode="decimal" [(ngModel)]="criteria.prixUnitaireMin" id="2-1"></p-inputNumber>
                        </div>
                        <div class="lg:col-3 md:col-6 sm:col-12 mb-4">
                            <label  class="font-bold block mb-2" for="2-2">{{'achatItem.prixUnitaireMax' | translate}}</label>
                            <p-inputNumber  mode="decimal" [(ngModel)]="criteria.prixUnitaireMax" id="2-2"></p-inputNumber>
                       </div>
                        <div class="lg:col-3 md:col-6 sm:col-12 mb-4">
                            <label  class="font-bold block mb-2" for="3-1">{{'achatItem.prixVenteMin' | translate}}</label>
                            <p-inputNumber  mode="decimal" [(ngModel)]="criteria.prixVenteMin" id="3-1"></p-inputNumber>
                        </div>
                        <div class="lg:col-3 md:col-6 sm:col-12 mb-4">
                            <label  class="font-bold block mb-2" for="3-2">{{'achatItem.prixVenteMax' | translate}}</label>
                            <p-inputNumber  mode="decimal" [(ngModel)]="criteria.prixVenteMax" id="3-2"></p-inputNumber>
                       </div>
                        <div class="lg:col-3 md:col-6 sm:col-12 mb-4">
                            <label  class="font-bold block mb-2" for="4-1">{{'achatItem.quantiteMin' | translate}}</label>
                            <p-inputNumber  mode="decimal" [(ngModel)]="criteria.quantiteMin" id="4-1"></p-inputNumber>
                        </div>
                        <div class="lg:col-3 md:col-6 sm:col-12 mb-4">
                            <label  class="font-bold block mb-2" for="4-2">{{'achatItem.quantiteMax' | translate}}</label>
                            <p-inputNumber  mode="decimal" [(ngModel)]="criteria.quantiteMax" id="4-2"></p-inputNumber>
                       </div>
                        <div class="lg:col-3 md:col-6 sm:col-12 mb-4">
                            <label  class="font-bold block mb-2" for="5-1">{{'achatItem.quantiteAvoirMin' | translate}}</label>
                            <p-inputNumber  mode="decimal" [(ngModel)]="criteria.quantiteAvoirMin" id="5-1"></p-inputNumber>
                        </div>
                        <div class="lg:col-3 md:col-6 sm:col-12 mb-4">
                            <label  class="font-bold block mb-2" for="5-2">{{'achatItem.quantiteAvoirMax' | translate}}</label>
                            <p-inputNumber  mode="decimal" [(ngModel)]="criteria.quantiteAvoirMax" id="5-2"></p-inputNumber>
                       </div>
                        <div class="lg:col-3 md:col-6 sm:col-12 mb-4">
                            <label  class="font-bold block mb-2" for="6-1">{{'achatItem.remiseMin' | translate}}</label>
                            <p-inputNumber  mode="decimal" [(ngModel)]="criteria.remiseMin" id="6-1"></p-inputNumber>
                        </div>
                        <div class="lg:col-3 md:col-6 sm:col-12 mb-4">
                            <label  class="font-bold block mb-2" for="6-2">{{'achatItem.remiseMax' | translate}}</label>
                            <p-inputNumber  mode="decimal" [(ngModel)]="criteria.remiseMax" id="6-2"></p-inputNumber>
                       </div>
                        <div class="lg:col-3 md:col-6 sm:col-12 mb-4">
                            <label  class="font-bold block mb-2" for="7-2">{{'achatItem.achat' | translate}} Max</label>
                            <p-dropdown [options]="achats" [(ngModel)]="criteria.achat" id="7" [filter]="true" class="p-fluid"
                                        [showClear]="true"  placeholder="{{'achatItem.achat' | translate}}" optionLabel="reference">
                            </p-dropdown>
                        </div>
                    </div>
                    <div [style]="{ marginTop : '1rem', display: 'flex', justifyContent: 'flex-end' }">
                        <button pButton pRipple label="{{'validate' | translate}}" icon="pi pi-sort-amount-down" class="p-button-info mr-2" (click)="findPaginatedByCriteria()"></button>
                    </div>
                </div>


            </p-toolbar>


            <p-table #dt [value]="items" [columns]="cols" [rows]="8" [paginator]="false"
                    [globalFilterFields]="['produitreference', 'prixUnitaire', 'prixVente', 'quantite', 'quantiteAvoir', 'remise', 'achatreference']" [(selection)]="selections"
                    [rowHover]="true" dataKey="id" styleClass="p-datatable-customers"
                    currentPageReportTemplate="{{'les éléments de {first} à {last} sur {totalRecords} ' | translate}}"
                    [showCurrentPageReport]="true" [rowsPerPageOptions]="[10,25,50]" selectionMode="multiple">
                <ng-template pTemplate="caption">
                    <div class="flex flex-column flex-row justify-content-between table-header">
                        <h5 class="p-m-0">{{'achatItem.header' | translate}}</h5>
                        <span class="p-input-icon-left ml-auto">
                            <i class="pi pi-search"></i>
                            <input pInputText type="text" placeholder="{{'searchInput' | translate}}" (input)="dt.filterGlobal($event.target.value, 'contains')"/>
                        </span>
                    </div>
                </ng-template>
                <ng-template pTemplate="header">
                    <tr>
                        <th style="width: 3rem">
                            <p-tableHeaderCheckbox></p-tableHeaderCheckbox>
                        </th>
                                
                        <th pSortableColumn="produit">
                            <div class="p-d-flex p-jc-between p-ai-center">
                                <span>{{'achatItem.produit' | translate}}</span>
                                <p-sortIcon field="produit"></p-sortIcon>
                            </div>
                        </th>
                                
                                
                        <th pSortableColumn="prixUnitaire">
                            <div class="p-d-flex p-jc-between p-ai-center">
                                <span>{{'achatItem.prixUnitaire' | translate}}</span>
                                <p-sortIcon field="prixUnitaire"></p-sortIcon>
                            </div>
                        </th>
                                
                                
                        <th pSortableColumn="prixVente">
                            <div class="p-d-flex p-jc-between p-ai-center">
                                <span>{{'achatItem.prixVente' | translate}}</span>
                                <p-sortIcon field="prixVente"></p-sortIcon>
                            </div>
                        </th>
                                
                                
                        <th pSortableColumn="quantite">
                            <div class="p-d-flex p-jc-between p-ai-center">
                                <span>{{'achatItem.quantite' | translate}}</span>
                                <p-sortIcon field="quantite"></p-sortIcon>
                            </div>
                        </th>
                                
                                
                        <th pSortableColumn="quantiteAvoir">
                            <div class="p-d-flex p-jc-between p-ai-center">
                                <span>{{'achatItem.quantiteAvoir' | translate}}</span>
                                <p-sortIcon field="quantiteAvoir"></p-sortIcon>
                            </div>
                        </th>
                                
                                
                        <th pSortableColumn="remise">
                            <div class="p-d-flex p-jc-between p-ai-center">
                                <span>{{'achatItem.remise' | translate}}</span>
                                <p-sortIcon field="remise"></p-sortIcon>
                            </div>
                        </th>
                                
                                
                        <th pSortableColumn="achat">
                            <div class="p-d-flex p-jc-between p-ai-center">
                                <span>{{'achatItem.achat' | translate}}</span>
                                <p-sortIcon field="achat"></p-sortIcon>
                            </div>
                        </th>
                                
                        <th>Actions</th>
                    </tr>
                </ng-template>
                <ng-template pTemplate="body" let-element>
                    <tr>
                        <td>
                            <p-tableCheckbox [value]="element"></p-tableCheckbox>
                        </td>
                            
                        <td>{{element.produit?.reference}}</td>
                            
                            
                        <td>{{element.prixUnitaire}}</td>
                            
                            
                        <td>{{element.prixVente}}</td>
                            
                            
                        <td>{{element.quantite}}</td>
                            
                            
                        <td>{{element.quantiteAvoir}}</td>
                            
                            
                        <td>{{element.remise}}</td>
                            
                            
                        <td>{{element.achat?.reference}}</td>
                            
                        <td>
                            <button pButton pRipple icon="pi pi-pencil"  class="p-button-rounded p-button-success mr-2" (click)="edit(element)"></button>
                            <button pButton pRipple icon="pi pi-list" class="p-button-rounded p-button-info mr-2" (click)="view(element)"></button>
                            <button pButton pRipple icon="pi pi-trash" class="p-button-rounded p-button-danger mr-2" (click)="delete(element)"></button>
                            <button pButton pRipple icon="pi pi-copy" class="p-button-rounded p-button-raised p-button-warning mr-2" (click)="duplicate(element)"></button>
                        </td>
                    </tr>
                </ng-template>

                <ng-template pTemplate="summary">
                    <p-paginator  [rows]="10" [totalRecords]="totalRecords" (onPageChange)="onPage($event)"></p-paginator>
                    <div class="p-d-flex p-ai-center p-jc-between">
                        En totale il {{items ? totalRecords == 1 ? 'y a' : 'y a' : 'y a' }} {{items ? totalRecords : 0 }} {{items ? totalRecords == 1 ? 'achat item' : 'achat items' : 0 }}.
                    </div>
                </ng-template>
            </p-table>
        </div>

        <app-achat-item-create-admin  *ngIf="createDialog"></app-achat-item-create-admin>
        <app-achat-item-edit-admin  *ngIf="editDialog"></app-achat-item-edit-admin>
        <app-achat-item-view-admin  *ngIf="viewDialog"></app-achat-item-view-admin>
        <p-confirmDialog [style]="{width: '450px'}"></p-confirmDialog>
    </div>
</div>

// error-ng-build-list-hook/frontend-react-v2/app/component/admin/view/stock/achat-item/list/achat-item-list-admin.component.tsx
import {Button} from 'primereact/button';
import {Column} from 'primereact/column';


import {DataTable} from 'primereact/datatable';
import {Dialog} from 'primereact/dialog';
import {FileUpload} from 'primereact/fileupload';
import {InputText} from 'primereact/inputtext';
import {Toast} from 'primereact/toast';
import {Toolbar} from 'primereact/toolbar';
import React, {useEffect, useRef, useState} from 'react';
import {Paginator, PaginatorPageChangeEvent} from 'primereact/paginator';
import {Card} from 'primereact/card';
import {Calendar} from 'primereact/calendar';
import {InputNumber} from 'primereact/inputnumber';
import {Dropdown} from 'primereact/dropdown';
import {format} from "date-fns";
import useListHook from "app/component/zyhook/useListhook";
import {MessageService} from 'app/zynerator/service/MessageService';


import {AchatItemAdminService} from 'app/controller/service/admin/stock/AchatItemAdminService.service';
import {AchatItemDto}  from 'app/controller/model/stock/AchatItem.model';
import {AchatItemCriteria} from 'app/controller/criteria/stock/AchatItemCriteria.model';

import {ProduitDto} from 'app/controller/model/commun/Produit.model';
import {ProduitAdminService} from 'app/controller/service/admin/commun/ProduitAdminService.service';
import {AchatDto} from 'app/controller/model/stock/Achat.model';
import {AchatAdminService} from 'app/controller/service/admin/stock/AchatAdminService.service';

import { useTranslation } from 'react-i18next';

import Edit from '../edit/achat-item-edit-admin.component';
import Create from '../create/achat-item-create-admin.component';
import View from '../view/achat-item-view-admin.component';


const List = () => {

    const { t } = useTranslation();

    const emptyItem = new AchatItemDto();
    const emptyCriteria = new AchatItemCriteria();
    const service = new AchatItemAdminService();


    const {
        items,
        showSearch,
        deleteItemDialog,
        item,
        selectedItems,
        setSelectedItems,
        hideDeleteItemDialog,
        globalFilter,
        setGlobalFilter,
        showCreateDialog,
        setShowCreateDialog,
        showEditDialog,
        setShowEditDialog,
        showViewDialog,
        setShowViewDialog,
        selectedItem,
        setSelectedItem,
        rows,
        totalRecords,
        criteria,
        setCriteria,
        first,
        fetchItems,
        toast,
        dt,
        findByCriteriaShow,
        handleCancelClick,
        confirmDeleteSelected,
        exportCSV,
        deleteItem,
        deleteItemDialogFooter,
        leftToolbarTemplate,
        rightToolbarTemplate,
        actionBodyTemplate,
        CustomBooleanCell,
        handleValidateClick,
        onPage,
        showCreateModal,
        showEditModal,
        showViewModal,
        add,
        update,
        confirmDeleteItem,
        statusBodyTemplate,
        formateDate,
        deleteSelectedItems,
        deleteItemsDialog,
        deleteItemsDialogFooter,
        hideDeleteItemsDialog
    } = useListHook<AchatItemDto, AchatItemCriteria>({ emptyItem, emptyCriteria,service, t})



    const [produits, setProduits] = useState<ProduitDto[]>([]);
    const [achats, setAchats] = useState<AchatDto[]>([]);

    const produitAdminService = new ProduitAdminService();
    const achatAdminService = new AchatAdminService();

    useEffect(() => {

        produitAdminService.getList().then(({data}) => setProduits(data)).catch(error => console.log(error));
        achatAdminService.getList().then(({data}) => setAchats(data)).catch(error => console.log(error));
        fetchItems(criteria);
    }, []);



    const header = (
    <div className="flex flex-column md:flex-row md:justify-content-between md:align-items-center">
        <h5 className="m-0">{t("achatItem.header")}</h5>
        <span className="block mt-2 md:mt-0 p-input-icon-left"><i className="pi pi-search"/>
            <InputText type="search" onInput={(e) => setGlobalFilter(e.currentTarget.value)}
                       placeholder={t("search")}/> </span>
    </div>
    );
    return (
    <div className="grid crud-demo">
        <div className="col-12">
            <div className="card">
                <Toast ref={toast} />
                <Toolbar className="mb-4" left={leftToolbarTemplate} right={rightToolbarTemplate}></Toolbar>
                {findByCriteriaShow && (
                <Card title={t("search")} className="mb-5">
                        <div className="grid">
                            <div className="flex flex-column col-3">
                                <label className="mb-1"  htmlFor="1">{t("achatItem.produitPlaceHolder")}</label>
                                <Dropdown id="1" value={criteria.produit} options={produits} onChange={(e) => setCriteria({ ...criteria, produit: e.target.value })} optionLabel="reference" filter showClear/>
                            </div>
                            <div className="flex flex-column col-3">
                                <label className="mb-1"  htmlFor="2-1">{t("achatItem.prixUnitaireMin")}</label>
                                <InputNumber id="2-1" value={criteria.prixUnitaireMin} onChange={(e) => setCriteria({ ...criteria, prixUnitaireMin: e.value })} mode="decimal" />
                            </div>
                            <div className="flex flex-column col-3">
                                <label className="mb-1"  htmlFor="2-2">{t("achatItem.prixUnitaireMax")}  </label>
                                <InputNumber id="2-2" value={criteria.prixUnitaireMax} onChange={(e) => setCriteria({ ...criteria, prixUnitaireMax: e.value })} mode="decimal" />
                            </div>
                            <div className="flex flex-column col-3">
                                <label className="mb-1"  htmlFor="3-1">{t("achatItem.prixVenteMin")}</label>
                                <InputNumber id="3-1" value={criteria.prixVenteMin} onChange={(e) => setCriteria({ ...criteria, prixVenteMin: e.value })} mode="decimal" />
                            </div>
                            <div className="flex flex-column col-3">
                                <label className="mb-1"  htmlFor="3-2">{t("achatItem.prixVenteMax")}  </label>
                                <InputNumber id="3-2" value={criteria.prixVenteMax} onChange={(e) => setCriteria({ ...criteria, prixVenteMax: e.value })} mode="decimal" />
                            </div>
                            <div className="flex flex-column col-3">
                                <label className="mb-1"  htmlFor="4-1">{t("achatItem.quantiteMin")}</label>
                                <InputNumber id="4-1" value={criteria.quantiteMin} onChange={(e) => setCriteria({ ...criteria, quantiteMin: e.value })} mode="decimal" />
                            </div>
                            <div className="flex flex-column col-3">
                                <label className="mb-1"  htmlFor="4-2">{t("achatItem.quantiteMax")}  </label>
                                <InputNumber id="4-2" value={criteria.quantiteMax} onChange={(e) => setCriteria({ ...criteria, quantiteMax: e.value })} mode="decimal" />
                            </div>
                            <div className="flex flex-column col-3">
                                <label className="mb-1"  htmlFor="5-1">{t("achatItem.quantiteAvoirMin")}</label>
                                <InputNumber id="5-1" value={criteria.quantiteAvoirMin} onChange={(e) => setCriteria({ ...criteria, quantiteAvoirMin: e.value })} mode="decimal" />
                            </div>
                            <div className="flex flex-column col-3">
                                <label className="mb-1"  htmlFor="5-2">{t("achatItem.quantiteAvoirMax")}  </label>
                                <InputNumber id="5-2" value={criteria.quantiteAvoirMax} onChange={(e) => setCriteria({ ...criteria, quantiteAvoirMax: e.value })} mode="decimal" />
                            </div>
                            <div className="flex flex-column col-3">
                                <label className="mb-1"  htmlFor="6-1">{t("achatItem.remiseMin")}</label>
                                <InputNumber id="6-1" value={criteria.remiseMin} onChange={(e) => setCriteria({ ...criteria, remiseMin: e.value })} mode="decimal" />
                            </div>
                            <div className="flex flex-column col-3">
                                <label className="mb-1"  htmlFor="6-2">{t("achatItem.remiseMax")}  </label>
                                <InputNumber id="6-2" value={criteria.remiseMax} onChange={(e) => setCriteria({ ...criteria, remiseMax: e.value })} mode="decimal" />
                            </div>
                            <div className="flex flex-column col-3">
                                <label className="mb-1"  htmlFor="7">{t("achatItem.achatPlaceHolder")}</label>
                                <Dropdown id="7" value={criteria.achat} options={achats} onChange={(e) => setCriteria({ ...criteria, achat: e.target.value })} optionLabel="reference" filter showClear/>
                            </div>
                        </div>
                        <div style={{ marginTop : '1rem', display: 'flex', justifyContent: 'flex-end' }} >
                            <Button label={t("validate")} icon="pi pi-sort-amount-down" className="p-button-info mr-2" onClick={handleValidateClick} />
                            <Button label={t("cancel")} className="p-button-secondary mr-2"  icon="pi pi-times" onClick={handleCancelClick} />
                        </div>
                </Card>
                )}
                <DataTable ref={dt} value={items} selection={selectedItems} onSelectionChange={(e) => setSelectedItems(e.value as AchatItemDto[])} dataKey="id" className="datatable-responsive" globalFilter={globalFilter} header={header} responsiveLayout="scroll" >
                    <Column selectionMode="multiple" headerStyle={{ width: '4rem' }}> </Column>
                    
                    <Column field="produit.reference" header={t("achatItem.produit")} sortable ></Column>
                    
                    
                    <Column field="prixUnitaire" header={t("achatItem.prixUnitaire")} sortable></Column>
                    
                    
                    <Column field="prixVente" header={t("achatItem.prixVente")} sortable></Column>
                    
                    
                    <Column field="quantite" header={t("achatItem.quantite")} sortable></Column>
                    
                    
                    <Column field="quantiteAvoir" header={t("achatItem.quantiteAvoir")} sortable></Column>
                    
                    
                    <Column field="remise" header={t("achatItem.remise")} sortable></Column>
                    
                    
                    <Column field="achat.reference" header={t("achatItem.achat")} sortable ></Column>
                    
                    <Column header={t("actions")} body={actionBodyTemplate}></Column>
                </DataTable>
                <div className="p-d-flex p-ai-center p-jc-between">
                    <Paginator onPageChange={onPage} first={first} rows={rows} totalRecords={totalRecords} />
                </div>
                {showCreateDialog && <Create visible={showCreateDialog} onClose={() => setShowCreateDialog(false)} add={add} showToast={toast} list={items} service={service} t={t} />}

                {showEditDialog && <Edit  visible={showEditDialog} onClose={() =>  { setShowEditDialog(false); setSelectedItem(emptyItem); }} showToast={toast} selectedItem={selectedItem} update={update} list={items} service={service}   t={t} />}

                {showViewDialog && <View visible={showViewDialog} onClose={() =>  { setShowViewDialog(false); setSelectedItem(emptyItem); }} selectedItem={selectedItem}   t={t} />}
                <Dialog visible={deleteItemDialog} style={{width: '450px'}} header={t("confirm")} modal footer={deleteItemDialogFooter} onHide={hideDeleteItemDialog}>
                    <div className="flex align-items-center justify-content-center">
                    <i className="pi pi-exclamation-triangle mr-3" style={{fontSize: '2rem'}}/>
                    {item && (<span>{t("achatItem.deleteAchatItemConfirmationMessage")} <b>{item.id}</b>?</span>)}
                    </div>
                </Dialog>

            <Dialog visible={deleteItemsDialog} style={{ width: '450px' }} header="Confirm" modal footer={deleteItemsDialogFooter} onHide={hideDeleteItemsDialog} >
                <div className="flex align-items-center justify-content-center">
                    <i className="pi pi-exclamation-triangle mr-3" style={{ fontSize: '2rem' }} />
                    {item && <span>{t("achatItem.deleteAchatItemsConfirmationMessage")}</span>}
                </div>
            </Dialog>

            </div>
        </div>
    </div>
);
};
export default List;
