// frontend-next-v1/app/component/admin/view/commun/produit/list/produit-list-admin.component.tsx
import {Button} from 'primereact/button';
import {Column} from 'primereact/column';


import {DataTable} from 'primereact/datatable';
import {Dialog} from 'primereact/dialog';
import {FileUpload} from 'primereact/fileupload';
import {InputText} from 'primereact/inputtext';
import {Toast} from 'primereact/toast';
import {Toolbar} from 'primereact/toolbar';
import React, {useEffect, useRef, useState} from 'react';
import {Paginator, PaginatorPageChangeEvent} from 'primereact/paginator';
import {Card} from 'primereact/card';
import {Calendar} from 'primereact/calendar';
import {InputNumber} from 'primereact/inputnumber';
import {Dropdown} from 'primereact/dropdown';
import {format} from "date-fns";
import useListHook from "app/component/zyhook/useListhook";
import {MessageService} from 'app/zynerator/service/MessageService';


import {ProduitAdminService} from 'app/controller/service/admin/commun/ProduitAdminService.service';
import {ProduitDto}  from 'app/controller/model/commun/Produit.model';
import {ProduitCriteria} from 'app/controller/criteria/commun/ProduitCriteria.model';


import { useTranslation } from 'react-i18next';

import Edit from '../edit/produit-edit-admin.component';
import Create from '../create/produit-create-admin.component';
import View from '../view/produit-view-admin.component';


const List = () => {

    const { t } = useTranslation();

    const emptyItem = new ProduitDto();
    const emptyCriteria = new ProduitCriteria();
    const service = new ProduitAdminService();


    const {
        items,
        showSearch,
        deleteItemDialog,
        item,
        selectedItems,
        setSelectedItems,
        hideDeleteItemDialog,
        globalFilter,
        setGlobalFilter,
        showCreateDialog,
        setShowCreateDialog,
        showEditDialog,
        setShowEditDialog,
        showViewDialog,
        setShowViewDialog,
        selectedItem,
        setSelectedItem,
        rows,
        totalRecords,
        criteria,
        setCriteria,
        first,
        fetchItems,
        toast,
        dt,
        findByCriteriaShow,
        handleCancelClick,
        confirmDeleteSelected,
        exportCSV,
        deleteItem,
        deleteItemDialogFooter,
        leftToolbarTemplate,
        rightToolbarTemplate,
        actionBodyTemplate,
        CustomBooleanCell,
        handleValidateClick,
        onPage,
        showCreateModal,
        showEditModal,
        showViewModal,
        add,
        update,
        confirmDeleteItem,
        statusBodyTemplate,
        formateDate,
        deleteSelectedItems,
        deleteItemsDialog,
        deleteItemsDialogFooter,
        hideDeleteItemsDialog
    } = useListHook<ProduitDto, ProduitCriteria>({ emptyItem, emptyCriteria,service, t})





    useEffect(() => {

        fetchItems(criteria);
    }, []);



    const header = (
    <div className="flex flex-column md:flex-row md:justify-content-between md:align-items-center">
        <h5 className="m-0">{t("produit.header")}</h5>
        <span className="block mt-2 md:mt-0 p-input-icon-left"><i className="pi pi-search"/>
            <InputText type="search" onInput={(e) => setGlobalFilter(e.currentTarget.value)}
                       placeholder={t("search")}/> </span>
    </div>
    );
    return (
    <div className="grid crud-demo">
        <div className="col-12">
            <div className="card">
                <Toast ref={toast} />
                <Toolbar className="mb-4" left={leftToolbarTemplate} right={rightToolbarTemplate}></Toolbar>
                {findByCriteriaShow && (
                <Card title={t("search")} className="mb-5">
                        <div className="grid">
                            <div className="flex flex-column col-3">
                                <label className="mb-1"  htmlFor="1">{t("produit.reference")}</label>
                                <InputText id="1" value={criteria.reference} onChange={(e) => setCriteria({ ...criteria, reference: e.target.value })} />
                            </div>
                            <div className="flex flex-column col-3">
                                <label className="mb-1"  htmlFor="2">{t("produit.libelle")}</label>
                                <InputText id="2" value={criteria.libelle} onChange={(e) => setCriteria({ ...criteria, libelle: e.target.value })} />
                            </div>
                            <div className="flex flex-column col-3">
                                <label className="mb-1"  htmlFor="3">{t("produit.barcode")}</label>
                                <InputText id="3" value={criteria.barcode} onChange={(e) => setCriteria({ ...criteria, barcode: e.target.value })} />
                            </div>
                            <div className="flex flex-column col-3">
                                <label className="mb-1"  htmlFor="4">{t("produit.discription")}</label>
                                <InputText id="4" value={criteria.discription} onChange={(e) => setCriteria({ ...criteria, discription: e.target.value })} />
                            </div>
                            <div className="flex flex-column col-3">
                                <label className="mb-1"  htmlFor="5-1">{t("produit.prixAchatMoyenMin")}</label>
                                <InputNumber id="5-1" value={criteria.prixAchatMoyenMin} onChange={(e) => setCriteria({ ...criteria, prixAchatMoyenMin: e.value })} mode="decimal" />
                            </div>
                            <div className="flex flex-column col-3">
                                <label className="mb-1"  htmlFor="5-2">{t("produit.prixAchatMoyenMax")}  </label>
                                <InputNumber id="5-2" value={criteria.prixAchatMoyenMax} onChange={(e) => setCriteria({ ...criteria, prixAchatMoyenMax: e.value })} mode="decimal" />
                            </div>
                            <div className="flex flex-column col-3">
                                <label className="mb-1"  htmlFor="6-1">{t("produit.quantiteMin")}</label>
                                <InputNumber id="6-1" value={criteria.quantiteMin} onChange={(e) => setCriteria({ ...criteria, quantiteMin: e.value })} mode="decimal" />
                            </div>
                            <div className="flex flex-column col-3">
                                <label className="mb-1"  htmlFor="6-2">{t("produit.quantiteMax")}  </label>
                                <InputNumber id="6-2" value={criteria.quantiteMax} onChange={(e) => setCriteria({ ...criteria, quantiteMax: e.value })} mode="decimal" />
                            </div>
                            <div className="flex flex-column col-3">
                                <label className="mb-1"  htmlFor="7-1">{t("produit.seuilAlertMin")}</label>
                                <InputNumber id="7-1" value={criteria.seuilAlertMin} onChange={(e) => setCriteria({ ...criteria, seuilAlertMin: e.value })} mode="decimal" />
                            </div>
                            <div className="flex flex-column col-3">
                                <label className="mb-1"  htmlFor="7-2">{t("produit.seuilAlertMax")}  </label>
                                <InputNumber id="7-2" value={criteria.seuilAlertMax} onChange={(e) => setCriteria({ ...criteria, seuilAlertMax: e.value })} mode="decimal" />
                            </div>
                        </div>
                        <div style={{ marginTop : '1rem', display: 'flex', justifyContent: 'flex-end' }} >
                            <Button label={t("validate")} icon="pi pi-sort-amount-down" className="p-button-info mr-2" onClick={handleValidateClick} />
                            <Button label={t("cancel")} className="p-button-secondary mr-2"  icon="pi pi-times" onClick={handleCancelClick} />
                        </div>
                </Card>
                )}
                <DataTable ref={dt} value={items} selection={selectedItems} onSelectionChange={(e) => setSelectedItems(e.value as ProduitDto[])} dataKey="id" className="datatable-responsive" globalFilter={globalFilter} header={header} responsiveLayout="scroll" >
                    <Column selectionMode="multiple" headerStyle={{ width: '4rem' }}> </Column>
                    
                    <Column field="reference" header={t("produit.reference")} sortable></Column>
                    
                    
                    <Column field="libelle" header={t("produit.libelle")} sortable></Column>
                    
                    
                    <Column field="barcode" header={t("produit.barcode")} sortable></Column>
                    
                    
                    <Column field="discription" header={t("produit.discription")} sortable></Column>
                    
                    
                    <Column field="prixAchatMoyen" header={t("produit.prixAchatMoyen")} sortable></Column>
                    
                    
                    <Column field="quantite" header={t("produit.quantite")} sortable></Column>
                    
                    
                    <Column field="seuilAlert" header={t("produit.seuilAlert")} sortable></Column>
                    
                    <Column header={t("actions")} body={actionBodyTemplate}></Column>
                </DataTable>
                <div className="p-d-flex p-ai-center p-jc-between">
                    <Paginator onPageChange={onPage} first={first} rows={rows} totalRecords={totalRecords} />
                </div>
                {showCreateDialog && <Create visible={showCreateDialog} onClose={() => setShowCreateDialog(false)} add={add} showToast={toast} list={items} service={service} t={t} />}

                {showEditDialog && <Edit  visible={showEditDialog} onClose={() =>  { setShowEditDialog(false); setSelectedItem(emptyItem); }} showToast={toast} selectedItem={selectedItem} update={update} list={items} service={service}   t={t} />}

                {showViewDialog && <View visible={showViewDialog} onClose={() =>  { setShowViewDialog(false); setSelectedItem(emptyItem); }} selectedItem={selectedItem}   t={t} />}
                <Dialog visible={deleteItemDialog} style={{width: '450px'}} header={t("confirm")} modal footer={deleteItemDialogFooter} onHide={hideDeleteItemDialog}>
                    <div className="flex align-items-center justify-content-center">
                    <i className="pi pi-exclamation-triangle mr-3" style={{fontSize: '2rem'}}/>
                    {item && (<span>{t("produit.deleteProduitConfirmationMessage")} <b>{item.reference}</b>?</span>)}
                    </div>
                </Dialog>

            <Dialog visible={deleteItemsDialog} style={{ width: '450px' }} header="Confirm" modal footer={deleteItemsDialogFooter} onHide={hideDeleteItemsDialog} >
                <div className="flex align-items-center justify-content-center">
                    <i className="pi pi-exclamation-triangle mr-3" style={{ fontSize: '2rem' }} />
                    {item && <span>{t("produit.deleteProduitsConfirmationMessage")}</span>}
                </div>
            </Dialog>

            </div>
        </div>
    </div>
);
};
export default List;

// frontend-angular/src/app/module/admin/view/commun/produit/list/produit-list-admin.component.ts
import {Component, OnInit} from '@angular/core';
import {ProduitAdminService} from 'src/app/controller/service/admin/commun/ProduitAdmin.service';
import {ProduitDto} from 'src/app/controller/model/commun/Produit.model';
import {ProduitCriteria} from 'src/app/controller/criteria/commun/ProduitCriteria.model';
import {AbstractListController} from 'src/app/zynerator/controller/AbstractListController';
import { environment } from 'src/environments/environment';



@Component({
  selector: 'app-produit-list-admin',
  templateUrl: './produit-list-admin.component.html'
})
export class ProduitListAdminComponent extends AbstractListController<ProduitDto, ProduitCriteria, ProduitAdminService>  implements OnInit {

    fileName = 'Produit';



    constructor( private produitService: ProduitAdminService  ) {
        super(produitService);
    }

    ngOnInit(): void {
        this.findPaginatedByCriteria();
        this.initExport();
        this.initCol();
    }


    public initCol() {
        this.cols = [
            {field: 'reference', header: 'Reference'},
            {field: 'libelle', header: 'Libelle'},
            {field: 'barcode', header: 'Barcode'},
            {field: 'prixAchatMoyen', header: 'Prix achat moyen'},
            {field: 'quantite', header: 'Quantite'},
            {field: 'seuilAlert', header: 'Seuil alert'},
        ];
    }





   public prepareColumnExport(): void {
        this.exportData = this.items.map(e => {
            return {
                 'Reference': e.reference ,
                 'Libelle': e.libelle ,
                 'Barcode': e.barcode ,
                 'Discription': e.discription ,
                 'Prix achat moyen': e.prixAchatMoyen ,
                 'Quantite': e.quantite ,
                 'Seuil alert': e.seuilAlert ,
            }
        });

        this.criteriaData = [{
            'Reference': this.criteria.reference ? this.criteria.reference : environment.emptyForExport ,
            'Libelle': this.criteria.libelle ? this.criteria.libelle : environment.emptyForExport ,
            'Barcode': this.criteria.barcode ? this.criteria.barcode : environment.emptyForExport ,
            'Discription': this.criteria.discription ? this.criteria.discription : environment.emptyForExport ,
            'Prix achat moyen Min': this.criteria.prixAchatMoyenMin ? this.criteria.prixAchatMoyenMin : environment.emptyForExport ,
            'Prix achat moyen Max': this.criteria.prixAchatMoyenMax ? this.criteria.prixAchatMoyenMax : environment.emptyForExport ,
            'Quantite Min': this.criteria.quantiteMin ? this.criteria.quantiteMin : environment.emptyForExport ,
            'Quantite Max': this.criteria.quantiteMax ? this.criteria.quantiteMax : environment.emptyForExport ,
            'Seuil alert Min': this.criteria.seuilAlertMin ? this.criteria.seuilAlertMin : environment.emptyForExport ,
            'Seuil alert Max': this.criteria.seuilAlertMax ? this.criteria.seuilAlertMax : environment.emptyForExport ,
        }];
      }
}

<div class="grid">
    <div class="col-12">
        <p-toast></p-toast>
        <div class="card">
            <p-toolbar styleClass="mb-4">
                <ng-template pTemplate="left">
                                        <button pButton pRipple label=" {{'new' | translate}}" icon="pi pi-plus" class="p-button-success mr-2 mb-2" (click)="openCreate('Produit')"></button>
                    <button [disabled]="isSelectionDisabled()" pButton pRipple label=" {{'delete' | translate}}" icon="pi pi-trash" class="p-button-danger mr-2 mb-2" (click)=deleteMultiple()></button>
                    <button pButton pRipple label=" {{'search' | translate}}" icon="pi pi-{{findByCriteriaShow?'angle-down':'angle-right'}}" class="p-button-warning mr-2 mb-2" (click)="this.showSearch()"></button>
                </ng-template>
                <ng-template pTemplate="right">
                    <div class="flex">
                        <p-splitButton label=" {{'export' | translate}}" icon="pi pi-download" styleClass="p-button-help" [model]="excelPdfButons"></p-splitButton>
                    </div>
                </ng-template>

            </p-toolbar>
            <p-toolbar *ngIf="findByCriteriaShow">

                <div class="col-12">
                    <div class="flex flex-wrap p-fluid col-12">
                       <div class="lg:col-3 md:col-6 sm:col-12 mb-4">
                            <label  class="font-bold block mb-2" for="1">{{'produit.reference' | translate}}</label>
                            <input  class="w-full"  pInputText id="1" type="text"  [(ngModel)]="criteria.referenceLike">
                        </div>
                       <div class="lg:col-3 md:col-6 sm:col-12 mb-4">
                            <label  class="font-bold block mb-2" for="2">{{'produit.libelle' | translate}}</label>
                            <input  class="w-full"  pInputText id="2" type="text"  [(ngModel)]="criteria.libelleLike">
                        </div>
                       <div class="lg:col-3 md:col-6 sm:col-12 mb-4">
                            <label  class="font-bold block mb-2" for="3">{{'produit.barcode' | translate}}</label>
                            <input  class="w-full"  pInputText id="3" type="text"  [(ngModel)]="criteria.barcodeLike">
                        </div>
                       <div class="lg:col-3 md:col-6 sm:col-12 mb-4">
                            <label  class="font-bold block mb-2" for="4">{{'produit.discription' | translate}}</label>
                            <input  class="w-full"  pInputText id="4" type="text"  [(ngModel)]="criteria.discriptionLike">
                        </div>
                        <div class="lg:col-3 md:col-6 sm:col-12 mb-4">
                            <label  class="font-bold block mb-2" for="5-1">{{'produit.prixAchatMoyenMin' | translate}}</label>
                            <p-inputNumber  mode="decimal" [(ngModel)]="criteria.prixAchatMoyenMin" id="5-1"></p-inputNumber>
                        </div>
                        <div class="lg:col-3 md:col-6 sm:col-12 mb-4">
                            <label  class="font-bold block mb-2" for="5-2">{{'produit.prixAchatMoyenMax' | translate}}</label>
                            <p-inputNumber  mode="decimal" [(ngModel)]="criteria.prixAchatMoyenMax" id="5-2"></p-inputNumber>
                       </div>
                        <div class="lg:col-3 md:col-6 sm:col-12 mb-4">
                            <label  class="font-bold block mb-2" for="6-1">{{'produit.quantiteMin' | translate}}</label>
                            <p-inputNumber  mode="decimal" [(ngModel)]="criteria.quantiteMin" id="6-1"></p-inputNumber>
                        </div>
                        <div class="lg:col-3 md:col-6 sm:col-12 mb-4">
                            <label  class="font-bold block mb-2" for="6-2">{{'produit.quantiteMax' | translate}}</label>
                            <p-inputNumber  mode="decimal" [(ngModel)]="criteria.quantiteMax" id="6-2"></p-inputNumber>
                       </div>
                        <div class="lg:col-3 md:col-6 sm:col-12 mb-4">
                            <label  class="font-bold block mb-2" for="7-1">{{'produit.seuilAlertMin' | translate}}</label>
                            <p-inputNumber  mode="decimal" [(ngModel)]="criteria.seuilAlertMin" id="7-1"></p-inputNumber>
                        </div>
                        <div class="lg:col-3 md:col-6 sm:col-12 mb-4">
                            <label  class="font-bold block mb-2" for="7-2">{{'produit.seuilAlertMax' | translate}}</label>
                            <p-inputNumber  mode="decimal" [(ngModel)]="criteria.seuilAlertMax" id="7-2"></p-inputNumber>
                       </div>
                    </div>
                    <div [style]="{ marginTop : '1rem', display: 'flex', justifyContent: 'flex-end' }">
                        <button pButton pRipple label="{{'validate' | translate}}" icon="pi pi-sort-amount-down" class="p-button-info mr-2" (click)="findPaginatedByCriteria()"></button>
                    </div>
                </div>


            </p-toolbar>


            <p-table #dt [value]="items" [columns]="cols" [rows]="8" [paginator]="false"
                    [globalFilterFields]="['reference', 'libelle', 'barcode', 'prixAchatMoyen', 'quantite', 'seuilAlert']" [(selection)]="selections"
                    [rowHover]="true" dataKey="id" styleClass="p-datatable-customers"
                    currentPageReportTemplate="{{'les éléments de {first} à {last} sur {totalRecords} ' | translate}}"
                    [showCurrentPageReport]="true" [rowsPerPageOptions]="[10,25,50]" selectionMode="multiple">
                <ng-template pTemplate="caption">
                    <div class="flex flex-column flex-row justify-content-between table-header">
                        <h5 class="p-m-0">{{'produit.header' | translate}}</h5>
                        <span class="p-input-icon-left ml-auto">
                            <i class="pi pi-search"></i>
                            <input pInputText type="text" placeholder="{{'searchInput' | translate}}" (input)="dt.filterGlobal($event.target.value, 'contains')"/>
                        </span>
                    </div>
                </ng-template>
                <ng-template pTemplate="header">
                    <tr>
                        <th style="width: 3rem">
                            <p-tableHeaderCheckbox></p-tableHeaderCheckbox>
                        </th>
                                
                        <th pSortableColumn="reference">
                            <div class="p-d-flex p-jc-between p-ai-center">
                                <span>{{'produit.reference' | translate}}</span>
                                <p-sortIcon field="reference"></p-sortIcon>
                                <p-columnFilter type="text" field="element.reference" display="menu" class="ml-auto"></p-columnFilter>
                            </div>
                        </th>
                                
                                
                        <th pSortableColumn="libelle">
                            <div class="p-d-flex p-jc-between p-ai-center">
                                <span>{{'produit.libelle' | translate}}</span>
                                <p-sortIcon field="libelle"></p-sortIcon>
                                <p-columnFilter type="text" field="element.libelle" display="menu" class="ml-auto"></p-columnFilter>
                            </div>
                        </th>
                                
                                
                        <th pSortableColumn="barcode">
                            <div class="p-d-flex p-jc-between p-ai-center">
                                <span>{{'produit.barcode' | translate}}</span>
                                <p-sortIcon field="barcode"></p-sortIcon>
                                <p-columnFilter type="text" field="element.barcode" display="menu" class="ml-auto"></p-columnFilter>
                            </div>
                        </th>
                                
                                
                        <th pSortableColumn="prixAchatMoyen">
                            <div class="p-d-flex p-jc-between p-ai-center">
                                <span>{{'produit.prixAchatMoyen' | translate}}</span>
                                <p-sortIcon field="prixAchatMoyen"></p-sortIcon>
                            </div>
                        </th>
                                
                                
                        <th pSortableColumn="quantite">
                            <div class="p-d-flex p-jc-between p-ai-center">
                                <span>{{'produit.quantite' | translate}}</span>
                                <p-sortIcon field="quantite"></p-sortIcon>
                            </div>
                        </th>
                                
                                
                        <th pSortableColumn="seuilAlert">
                            <div class="p-d-flex p-jc-between p-ai-center">
                                <span>{{'produit.seuilAlert' | translate}}</span>
                                <p-sortIcon field="seuilAlert"></p-sortIcon>
                            </div>
                        </th>
                                
                        <th>Actions</th>
                    </tr>
                </ng-template>
                <ng-template pTemplate="body" let-element>
                    <tr>
                        <td>
                            <p-tableCheckbox [value]="element"></p-tableCheckbox>
                        </td>
                            
                        <td>{{element.reference}}</td>
                            
                            
                        <td>{{element.libelle}}</td>
                            
                            
                        <td>{{element.barcode}}</td>
                            
                            
                        <td>{{element.prixAchatMoyen}}</td>
                            
                            
                        <td>{{element.quantite}}</td>
                            
                            
                        <td>{{element.seuilAlert}}</td>
                            
                        <td>
                            <button pButton pRipple icon="pi pi-pencil"  class="p-button-rounded p-button-success mr-2" (click)="edit(element)"></button>
                            <button pButton pRipple icon="pi pi-list" class="p-button-rounded p-button-info mr-2" (click)="view(element)"></button>
                            <button pButton pRipple icon="pi pi-trash" class="p-button-rounded p-button-danger mr-2" (click)="delete(element)"></button>
                            <button pButton pRipple icon="pi pi-copy" class="p-button-rounded p-button-raised p-button-warning mr-2" (click)="duplicate(element)"></button>
                        </td>
                    </tr>
                </ng-template>

                <ng-template pTemplate="summary">
                    <p-paginator  [rows]="10" [totalRecords]="totalRecords" (onPageChange)="onPage($event)"></p-paginator>
                    <div class="p-d-flex p-ai-center p-jc-between">
                        En totale il {{items ? totalRecords == 1 ? 'y a' : 'y a' : 'y a' }} {{items ? totalRecords : 0 }} {{items ? totalRecords == 1 ? 'produit' : 'produits' : 0 }}.
                    </div>
                </ng-template>
            </p-table>
        </div>

        <app-produit-create-admin  *ngIf="createDialog"></app-produit-create-admin>
        <app-produit-edit-admin  *ngIf="editDialog"></app-produit-edit-admin>
        <app-produit-view-admin  *ngIf="viewDialog"></app-produit-view-admin>
        <p-confirmDialog [style]="{width: '450px'}"></p-confirmDialog>
    </div>
</div>
