// frontend-next-v1/app/component/admin/view/achat/achat/list/achat-list-admin.component.tsx
import {Button} from 'primereact/button';
import {Column} from 'primereact/column';


import {DataTable} from 'primereact/datatable';
import {Dialog} from 'primereact/dialog';
import {FileUpload} from 'primereact/fileupload';
import {InputText} from 'primereact/inputtext';
import {Toast} from 'primereact/toast';
import {Toolbar} from 'primereact/toolbar';
import React, {useEffect, useRef, useState} from 'react';
import {Paginator, PaginatorPageChangeEvent} from 'primereact/paginator';
import {Card} from 'primereact/card';
import {Calendar} from 'primereact/calendar';
import {InputNumber} from 'primereact/inputnumber';
import {Dropdown} from 'primereact/dropdown';
import {format} from "date-fns";
import useListHook from "app/component/zyhook/useListhook";
import {MessageService} from 'app/zynerator/service/MessageService';


import {AchatAdminService} from 'app/controller/service/admin/achat/AchatAdminService.service';
import {AchatDto}  from 'app/controller/model/achat/Achat.model';
import {AchatCriteria} from 'app/controller/criteria/achat/AchatCriteria.model';

import {ClientDto} from 'app/controller/model/commun/Client.model';
import {ClientAdminService} from 'app/controller/service/admin/commun/ClientAdminService.service';

import { useTranslation } from 'react-i18next';

import Edit from '../edit/achat-edit-admin.component';
import Create from '../create/achat-create-admin.component';
import View from '../view/achat-view-admin.component';


const List = () => {

    const { t } = useTranslation();

    const emptyItem = new AchatDto();
    const emptyCriteria = new AchatCriteria();
    const service = new AchatAdminService();


    const {
        items,
        showSearch,
        deleteItemDialog,
        item,
        selectedItems,
        setSelectedItems,
        hideDeleteItemDialog,
        globalFilter,
        setGlobalFilter,
        showCreateDialog,
        setShowCreateDialog,
        showEditDialog,
        setShowEditDialog,
        showViewDialog,
        setShowViewDialog,
        selectedItem,
        setSelectedItem,
        rows,
        totalRecords,
        criteria,
        setCriteria,
        first,
        fetchItems,
        toast,
        dt,
        findByCriteriaShow,
        handleCancelClick,
        confirmDeleteSelected,
        exportCSV,
        deleteItem,
        deleteItemDialogFooter,
        leftToolbarTemplate,
        rightToolbarTemplate,
        actionBodyTemplate,
        CustomBooleanCell,
        handleValidateClick,
        onPage,
        showCreateModal,
        showEditModal,
        showViewModal,
        add,
        update,
        confirmDeleteItem,
        statusBodyTemplate,
        formateDate,
        deleteSelectedItems,
        deleteItemsDialog,
        deleteItemsDialogFooter,
        hideDeleteItemsDialog
    } = useListHook<AchatDto, AchatCriteria>({ emptyItem, emptyCriteria,service, t})



    const [clients, setClients] = useState<ClientDto[]>([]);

    const clientAdminService = new ClientAdminService();

    useEffect(() => {

        clientAdminService.getList().then(({data}) => setClients(data)).catch(error => console.log(error));
        fetchItems(criteria);
    }, []);



    const header = (
    <div className="flex flex-column md:flex-row md:justify-content-between md:align-items-center">
        <h5 className="m-0">{t("achat.header")}</h5>
        <span className="block mt-2 md:mt-0 p-input-icon-left"><i className="pi pi-search"/>
            <InputText type="search" onInput={(e) => setGlobalFilter(e.currentTarget.value)}
                       placeholder={t("search")}/> </span>
    </div>
    );
    return (
    <div className="grid crud-demo">
        <div className="col-12">
            <div className="card">
                <Toast ref={toast} />
                <Toolbar className="mb-4" left={leftToolbarTemplate} right={rightToolbarTemplate}></Toolbar>
                {findByCriteriaShow && (
                <Card title={t("search")} className="mb-5">
                        <div className="grid">
                            <div className="flex flex-column col-3">
                                <label className="mb-1"  htmlFor="1">{t("achat.reference")}</label>
                                <InputText id="1" value={criteria.reference} onChange={(e) => setCriteria({ ...criteria, reference: e.target.value })} />
                            </div>
                            <div className="flex flex-column col-3">
                                <label className="mb-1"  htmlFor="2-1">{t("achat.dateAchatMin")}</label>
                                <Calendar id="2-1" value={criteria.dateAchatFrom} onChange={(e) => setCriteria({ ...criteria, dateAchatFrom: e.value as Date })} dateFormat="dd-MM-yy" showIcon={true} />
                            </div>
                            <div className="flex flex-column col-3">
                                <label className="mb-1"  htmlFor="2-2">{t("achat.dateAchatMax")}</label>
                                <Calendar id="2-2" value={criteria.dateAchatTo} onChange={(e) => setCriteria({ ...criteria, dateAchatTo: e.value as Date })} dateFormat="dd-MM-yy" showIcon={true} />
                            </div>
                            <div className="flex flex-column col-3">
                                <label className="mb-1"  htmlFor="3-1">{t("achat.totalMin")}</label>
                                <InputNumber id="3-1" value={criteria.totalMin} onChange={(e) => setCriteria({ ...criteria, totalMin: e.value })} mode="decimal" />
                            </div>
                            <div className="flex flex-column col-3">
                                <label className="mb-1"  htmlFor="3-2">{t("achat.totalMax")}  </label>
                                <InputNumber id="3-2" value={criteria.totalMax} onChange={(e) => setCriteria({ ...criteria, totalMax: e.value })} mode="decimal" />
                            </div>
                            <div className="flex flex-column col-3">
                                <label className="mb-1"  htmlFor="4-1">{t("achat.totalPayeMin")}</label>
                                <InputNumber id="4-1" value={criteria.totalPayeMin} onChange={(e) => setCriteria({ ...criteria, totalPayeMin: e.value })} mode="decimal" />
                            </div>
                            <div className="flex flex-column col-3">
                                <label className="mb-1"  htmlFor="4-2">{t("achat.totalPayeMax")}  </label>
                                <InputNumber id="4-2" value={criteria.totalPayeMax} onChange={(e) => setCriteria({ ...criteria, totalPayeMax: e.value })} mode="decimal" />
                            </div>
                            <div className="flex flex-column col-3">
                                <label className="mb-1"  htmlFor="5">{t("achat.description")}</label>
                                <InputText id="5" value={criteria.description} onChange={(e) => setCriteria({ ...criteria, description: e.target.value })} />
                            </div>
                            <div className="flex flex-column col-3">
                                <label className="mb-1"  htmlFor="6">{t("achat.clientPlaceHolder")}</label>
                                <Dropdown id="6" value={criteria.client} options={clients} onChange={(e) => setCriteria({ ...criteria, client: e.target.value })} optionLabel="nom" filter showClear/>
                            </div>
                        </div>
                        <div style={{ marginTop : '1rem', display: 'flex', justifyContent: 'flex-end' }} >
                            <Button label={t("validate")} icon="pi pi-sort-amount-down" className="p-button-info mr-2" onClick={handleValidateClick} />
                            <Button label={t("cancel")} className="p-button-secondary mr-2"  icon="pi pi-times" onClick={handleCancelClick} />
                        </div>
                </Card>
                )}
                <DataTable ref={dt} value={items} selection={selectedItems} onSelectionChange={(e) => setSelectedItems(e.value as AchatDto[])} dataKey="id" className="datatable-responsive" globalFilter={globalFilter} header={header} responsiveLayout="scroll" >
                    <Column selectionMode="multiple" headerStyle={{ width: '4rem' }}> </Column>
                    
                    <Column field="reference" header={t("achat.reference")} sortable></Column>
                    
                    
                    <Column field="dateAchat" header={t("achat.dateAchat")} sortable body={formateDate("dateAchat")}></Column>
                    
                    
                    <Column field="total" header={t("achat.total")} sortable></Column>
                    
                    
                    <Column field="totalPaye" header={t("achat.totalPaye")} sortable></Column>
                    
                    
                    <Column field="client.nom" header={t("achat.client")} sortable ></Column>
                    
                    <Column header={t("actions")} body={actionBodyTemplate}></Column>
                </DataTable>
                <div className="p-d-flex p-ai-center p-jc-between">
                    <Paginator onPageChange={onPage} first={first} rows={rows} totalRecords={totalRecords} />
                </div>
                {showCreateDialog && <Create visible={showCreateDialog} onClose={() => setShowCreateDialog(false)} add={add} showToast={toast} list={items} service={service} t={t} />}

                {showEditDialog && <Edit  visible={showEditDialog} onClose={() =>  { setShowEditDialog(false); setSelectedItem(emptyItem); }} showToast={toast} selectedItem={selectedItem} update={update} list={items} service={service}   t={t} />}

                {showViewDialog && <View visible={showViewDialog} onClose={() =>  { setShowViewDialog(false); setSelectedItem(emptyItem); }} selectedItem={selectedItem}   t={t} />}
                <Dialog visible={deleteItemDialog} style={{width: '450px'}} header={t("confirm")} modal footer={deleteItemDialogFooter} onHide={hideDeleteItemDialog}>
                    <div className="flex align-items-center justify-content-center">
                    <i className="pi pi-exclamation-triangle mr-3" style={{fontSize: '2rem'}}/>
                    {item && (<span>{t("achat.deleteAchatConfirmationMessage")} <b>{item.reference}</b>?</span>)}
                    </div>
                </Dialog>

            <Dialog visible={deleteItemsDialog} style={{ width: '450px' }} header="Confirm" modal footer={deleteItemsDialogFooter} onHide={hideDeleteItemsDialog} >
                <div className="flex align-items-center justify-content-center">
                    <i className="pi pi-exclamation-triangle mr-3" style={{ fontSize: '2rem' }} />
                    {item && <span>{t("achat.deleteAchatsConfirmationMessage")}</span>}
                </div>
            </Dialog>

            </div>
        </div>
    </div>
);
};
export default List;

// frontend-angular/src/app/module/admin/view/stock/achat/list/achat-list-admin.component.ts
import {Component, OnInit} from '@angular/core';
import {AchatAdminService} from 'src/app/controller/service/admin/stock/AchatAdmin.service';
import {AchatDto} from 'src/app/controller/model/stock/Achat.model';
import {AchatCriteria} from 'src/app/controller/criteria/stock/AchatCriteria.model';
import {AbstractListController} from 'src/app/zynerator/controller/AbstractListController';
import { environment } from 'src/environments/environment';

import {ProduitDto} from 'src/app/controller/model/commun/Produit.model';
import {ProduitAdminService} from 'src/app/controller/service/admin/commun/ProduitAdmin.service';
import {AchatItemDto} from 'src/app/controller/model/stock/AchatItem.model';
import {AchatItemAdminService} from 'src/app/controller/service/admin/stock/AchatItemAdmin.service';
import {ClientDto} from 'src/app/controller/model/commun/Client.model';
import {ClientAdminService} from 'src/app/controller/service/admin/commun/ClientAdmin.service';


@Component({
  selector: 'app-achat-list-admin',
  templateUrl: './achat-list-admin.component.html'
})
export class AchatListAdminComponent extends AbstractListController<AchatDto, AchatCriteria, AchatAdminService>  implements OnInit {

    fileName = 'Achat';

    clients: Array<ClientDto>;


    constructor( private achatService: AchatAdminService  , private produitService: ProduitAdminService, private achatItemService: AchatItemAdminService, private clientService: ClientAdminService) {
        super(achatService);
    }

    ngOnInit(): void {
        this.findPaginatedByCriteria();
        this.initExport();
        this.initCol();
        this.loadClient();
    }


    public initCol() {
        this.cols = [
            {field: 'reference', header: 'Reference'},
            {field: 'dateAchat', header: 'Date achat'},
            {field: 'total', header: 'Total'},
            {field: 'totalPaye', header: 'Total paye'},
            {field: 'client?.nom', header: 'Client'},
        ];
    }


    public async loadClient(){
       this.clientService.findAllOptimized().subscribe(clients => this.clients = clients, error => console.log(error))
    }

	public initDuplicate(res: AchatDto) {
        if (res.achatItems != null) {
             res.achatItems.forEach(d => { d.achat = null; d.id = null; });
        }
	}


   public prepareColumnExport(): void {
        this.exportData = this.items.map(e => {
            return {
                 'Reference': e.reference ,
                'Date achat': this.datePipe.transform(e.dateAchat , 'dd/MM/yyyy hh:mm'),
                 'Total': e.total ,
                 'Total paye': e.totalPaye ,
                 'Description': e.description ,
                'Client': e.client?.nom ,
            }
        });

        this.criteriaData = [{
            'Reference': this.criteria.reference ? this.criteria.reference : environment.emptyForExport ,
            'Date achat Min': this.criteria.dateAchatFrom ? this.datePipe.transform(this.criteria.dateAchatFrom , this.dateFormat) : environment.emptyForExport ,
            'Date achat Max': this.criteria.dateAchatTo ? this.datePipe.transform(this.criteria.dateAchatTo , this.dateFormat) : environment.emptyForExport ,
            'Total Min': this.criteria.totalMin ? this.criteria.totalMin : environment.emptyForExport ,
            'Total Max': this.criteria.totalMax ? this.criteria.totalMax : environment.emptyForExport ,
            'Total paye Min': this.criteria.totalPayeMin ? this.criteria.totalPayeMin : environment.emptyForExport ,
            'Total paye Max': this.criteria.totalPayeMax ? this.criteria.totalPayeMax : environment.emptyForExport ,
            'Description': this.criteria.description ? this.criteria.description : environment.emptyForExport ,
        //'Client': this.criteria.client?.nom ? this.criteria.client?.nom : environment.emptyForExport ,
        }];
      }
}

<div class="grid">
    <div class="col-12">
        <p-toast></p-toast>
        <div class="card">
            <p-toolbar styleClass="mb-4">
                <ng-template pTemplate="left">
                                        <button pButton pRipple label=" {{'new' | translate}}" icon="pi pi-plus" class="p-button-success mr-2 mb-2" (click)="openCreate('Achat')"></button>
                    <button [disabled]="isSelectionDisabled()" pButton pRipple label=" {{'delete' | translate}}" icon="pi pi-trash" class="p-button-danger mr-2 mb-2" (click)=deleteMultiple()></button>
                    <button pButton pRipple label=" {{'search' | translate}}" icon="pi pi-{{findByCriteriaShow?'angle-down':'angle-right'}}" class="p-button-warning mr-2 mb-2" (click)="this.showSearch()"></button>
                </ng-template>
                <ng-template pTemplate="right">
                    <div class="flex">
                        <p-splitButton label=" {{'export' | translate}}" icon="pi pi-download" styleClass="p-button-help" [model]="excelPdfButons"></p-splitButton>
                    </div>
                </ng-template>

            </p-toolbar>
            <p-toolbar *ngIf="findByCriteriaShow">

                <div class="col-12">
                    <div class="flex flex-wrap p-fluid col-12">
                       <div class="lg:col-3 md:col-6 sm:col-12 mb-4">
                            <label  class="font-bold block mb-2" for="1">{{'achat.reference' | translate}}</label>
                            <input  class="w-full"  pInputText id="1" type="text"  [(ngModel)]="criteria.referenceLike">
                        </div>

                        <div class="lg:col-3 md:col-6 sm:col-12 mb-4">
                            <label class="font-bold block mb-2" for="2-1">{{'achat.dateAchatMin' | translate}}</label>
                            <p-calendar class="mr-2" [(ngModel)]="criteria.dateAchatFrom"
                                    id="2-1" dateFormat="dd-MM-yy"  [showIcon]="true"  class="p-fluid"></p-calendar>
                        </div>

                        <div class="lg:col-3 md:col-6 sm:col-12 mb-4">
                            <label  class="font-bold block mb-2" for="2-2">{{'achat.dateAchatMax' | translate}}</label>
                            <p-calendar class="mr-2" [(ngModel)]="criteria.dateAchatTo"
                                    id="2-2" dateFormat="dd-MM-yy"  [showIcon]="true" class="p-fluid"></p-calendar>
                        </div>

                        <div class="lg:col-3 md:col-6 sm:col-12 mb-4">
                            <label  class="font-bold block mb-2" for="3-1">{{'achat.totalMin' | translate}}</label>
                            <p-inputNumber  mode="decimal" [(ngModel)]="criteria.totalMin" id="3-1"></p-inputNumber>
                        </div>
                        <div class="lg:col-3 md:col-6 sm:col-12 mb-4">
                            <label  class="font-bold block mb-2" for="3-2">{{'achat.totalMax' | translate}}</label>
                            <p-inputNumber  mode="decimal" [(ngModel)]="criteria.totalMax" id="3-2"></p-inputNumber>
                       </div>
                        <div class="lg:col-3 md:col-6 sm:col-12 mb-4">
                            <label  class="font-bold block mb-2" for="4-1">{{'achat.totalPayeMin' | translate}}</label>
                            <p-inputNumber  mode="decimal" [(ngModel)]="criteria.totalPayeMin" id="4-1"></p-inputNumber>
                        </div>
                        <div class="lg:col-3 md:col-6 sm:col-12 mb-4">
                            <label  class="font-bold block mb-2" for="4-2">{{'achat.totalPayeMax' | translate}}</label>
                            <p-inputNumber  mode="decimal" [(ngModel)]="criteria.totalPayeMax" id="4-2"></p-inputNumber>
                       </div>
                       <div class="lg:col-3 md:col-6 sm:col-12 mb-4">
                            <label  class="font-bold block mb-2" for="5">{{'achat.description' | translate}}</label>
                            <input  class="w-full"  pInputText id="5" type="text"  [(ngModel)]="criteria.descriptionLike">
                        </div>
                        <div class="lg:col-3 md:col-6 sm:col-12 mb-4">
                            <label  class="font-bold block mb-2" for="6-2">{{'achat.client' | translate}} Max</label>
                            <p-dropdown [options]="clients" [(ngModel)]="criteria.client" id="6" [filter]="true" class="p-fluid"
                                        [showClear]="true"  placeholder="{{'achat.client' | translate}}" optionLabel="nom">
                            </p-dropdown>
                        </div>
                    </div>
                    <div [style]="{ marginTop : '1rem', display: 'flex', justifyContent: 'flex-end' }">
                        <button pButton pRipple label="{{'validate' | translate}}" icon="pi pi-sort-amount-down" class="p-button-info mr-2" (click)="findPaginatedByCriteria()"></button>
                    </div>
                </div>


            </p-toolbar>


            <p-table #dt [value]="items" [columns]="cols" [rows]="8" [paginator]="false"
                    [globalFilterFields]="['reference', 'dateAchat', 'total', 'totalPaye', 'clientnom']" [(selection)]="selections"
                    [rowHover]="true" dataKey="id" styleClass="p-datatable-customers"
                    currentPageReportTemplate="{{'les éléments de {first} à {last} sur {totalRecords} ' | translate}}"
                    [showCurrentPageReport]="true" [rowsPerPageOptions]="[10,25,50]" selectionMode="multiple">
                <ng-template pTemplate="caption">
                    <div class="flex flex-column flex-row justify-content-between table-header">
                        <h5 class="p-m-0">{{'achat.header' | translate}}</h5>
                        <span class="p-input-icon-left ml-auto">
                            <i class="pi pi-search"></i>
                            <input pInputText type="text" placeholder="{{'searchInput' | translate}}" (input)="dt.filterGlobal($event.target.value, 'contains')"/>
                        </span>
                    </div>
                </ng-template>
                <ng-template pTemplate="header">
                    <tr>
                        <th style="width: 3rem">
                            <p-tableHeaderCheckbox></p-tableHeaderCheckbox>
                        </th>
                                
                        <th pSortableColumn="reference">
                            <div class="p-d-flex p-jc-between p-ai-center">
                                <span>{{'achat.reference' | translate}}</span>
                                <p-sortIcon field="reference"></p-sortIcon>
                                <p-columnFilter type="text" field="element.reference" display="menu" class="ml-auto"></p-columnFilter>
                            </div>
                        </th>
                                
                                
                        <th pSortableColumn="dateAchat">
                            <div class="p-d-flex p-jc-between p-ai-center">
                                <span>{{'achat.dateAchat' | translate}}</span>
                                <p-sortIcon field="dateAchat"></p-sortIcon>
                            </div>
                        </th>
                                
                                
                        <th pSortableColumn="total">
                            <div class="p-d-flex p-jc-between p-ai-center">
                                <span>{{'achat.total' | translate}}</span>
                                <p-sortIcon field="total"></p-sortIcon>
                            </div>
                        </th>
                                
                                
                        <th pSortableColumn="totalPaye">
                            <div class="p-d-flex p-jc-between p-ai-center">
                                <span>{{'achat.totalPaye' | translate}}</span>
                                <p-sortIcon field="totalPaye"></p-sortIcon>
                            </div>
                        </th>
                                
                                
                        <th pSortableColumn="client">
                            <div class="p-d-flex p-jc-between p-ai-center">
                                <span>{{'achat.client' | translate}}</span>
                                <p-sortIcon field="client"></p-sortIcon>
                            </div>
                        </th>
                                
                        <th>Actions</th>
                    </tr>
                </ng-template>
                <ng-template pTemplate="body" let-element>
                    <tr>
                        <td>
                            <p-tableCheckbox [value]="element"></p-tableCheckbox>
                        </td>
                            
                        <td>{{element.reference}}</td>
                            
                            
                        <td>{{element.dateAchat | date :'dd/MM/yyyy HH:mm' }}</td>
                            
                            
                        <td>{{element.total}}</td>
                            
                            
                        <td>{{element.totalPaye}}</td>
                            
                            
                        <td>{{element.client?.nom}}</td>
                            
                        <td>
                            <button pButton pRipple icon="pi pi-pencil"  class="p-button-rounded p-button-success mr-2" (click)="edit(element)"></button>
                            <button pButton pRipple icon="pi pi-list" class="p-button-rounded p-button-info mr-2" (click)="view(element)"></button>
                            <button pButton pRipple icon="pi pi-trash" class="p-button-rounded p-button-danger mr-2" (click)="delete(element)"></button>
                            <button pButton pRipple icon="pi pi-copy" class="p-button-rounded p-button-raised p-button-warning mr-2" (click)="duplicate(element)"></button>
                        </td>
                    </tr>
                </ng-template>

                <ng-template pTemplate="summary">
                    <p-paginator  [rows]="10" [totalRecords]="totalRecords" (onPageChange)="onPage($event)"></p-paginator>
                    <div class="p-d-flex p-ai-center p-jc-between">
                        En totale il {{items ? totalRecords == 1 ? 'y a' : 'y a' : 'y a' }} {{items ? totalRecords : 0 }} {{items ? totalRecords == 1 ? 'achat' : 'achats' : 0 }}.
                    </div>
                </ng-template>
            </p-table>
        </div>

        <app-achat-create-admin  *ngIf="createDialog"></app-achat-create-admin>
        <app-achat-edit-admin  *ngIf="editDialog"></app-achat-edit-admin>
        <app-achat-view-admin  *ngIf="viewDialog"></app-achat-view-admin>
        <p-confirmDialog [style]="{width: '450px'}"></p-confirmDialog>
    </div>
</div>
