// frontend-react/app/component/admin/view/stock/achat/create/achat-create-admin.component.tsx
import {Button} from 'primereact/button';
import {Column} from 'primereact/column';
import {TabView, TabPanel} from 'primereact/tabview';
import {DataTable} from 'primereact/datatable';
import {Dialog} from 'primereact/dialog';
import {InputNumber, InputNumberChangeEvent} from 'primereact/inputnumber';
import {InputText} from 'primereact/inputtext';
import {classNames} from 'primereact/utils';
import { InputTextarea } from 'primereact/inputtextarea';
import React, {useEffect, useState} from 'react';
import {Calendar, CalendarChangeEvent} from 'primereact/calendar';
import { format } from 'date-fns';
import {InputSwitch, InputSwitchChangeEvent} from 'primereact/inputswitch';
import {Dropdown, DropdownChangeEvent} from 'primereact/dropdown';
import {MultiSelect, MultiSelectChangeEvent} from 'primereact/multiselect';
import {MessageService} from 'app/zynerator/service/MessageService';

import {AchatAdminService} from 'app/controller/service/admin/stock/AchatAdminService.service';
import  {AchatDto}  from 'app/controller/model/stock/Achat.model';
import {AchatCriteria} from "app/controller/criteria/stock/AchatCriteria.model";

import {ProduitDto} from 'app/controller/model/commun/Produit.model';
import {ProduitAdminService} from 'app/controller/service/admin/commun/ProduitAdminService.service';
import {ClientDto} from 'app/controller/model/commun/Client.model';
import {ClientAdminService} from 'app/controller/service/admin/commun/ClientAdminService.service';
import {AchatItemDto} from 'app/controller/model/stock/AchatItem.model';
import {AchatItemAdminService} from 'app/controller/service/admin/stock/AchatItemAdminService.service';
import {TFunction} from "i18next";
import {Toast} from "primereact/toast";
import useCreateHook from "app/component/zyhook/useCreate.hook";



type AchatCreateAdminType = {
    visible: boolean,
    onClose: () => void,
    add: (item: AchatDto) => void,
    showToast: React.Ref<Toast>,
    list: AchatDto[],
    service: AchatAdminService,
    t: TFunction
}
const Create: React.FC<AchatCreateAdminType> = ({visible, onClose, add, showToast, list, service, t}) => {


    const isFormValid = () => {
    let errorMessages = new Array<string>();
                if(item.reference == '')
                errorMessages.push("reference is required")
        return errorMessages.length == 0 ;
    }
    const emptyItem = new AchatDto();
        const {
            item,
            setItem,
            submitted,
            setSubmitted,
            activeIndex,
            setActiveIndex,
            activeTab,
            setActiveTab,
            onInputTextChange,
            onInputDateChange,
            onInputNumerChange,
            onMultiSelectChange,
            onBooleanInputChange,
            onTabChange,
            onDropdownChange,
            hideDialog,
            saveItem,
            formateDate
        } = useCreateHook<AchatDto, AchatCriteria>({list, emptyItem, onClose, add, showToast,service, isFormValid})
    const [produits, setProduits] = useState<ProduitDto[]>([]);
    const [clients, setClients] = useState<ClientDto[]>([]);

    const [achatItems, setAchatItems] = useState<AchatItemDto>(new AchatItemDto());

    const produitAdminService = new ProduitAdminService();
    const clientAdminService = new ClientAdminService();
    const achatItemAdminService = new AchatItemAdminService();
    useEffect(() => {
        clientAdminService.getList().then(({data}) => setClients(data)).catch(error => console.log(error));

        produitAdminService.getList().then(({data}) => setProduits(data)).catch(error => console.log(error));


    }, []);




    const addAchatItems = () => {
        setSubmitted(true);
        if( item.achatItems == null )
        item.achatItems = new Array<AchatItemDto>();
        let _item = achatItems;
        if (!_item.id) {
            item.achatItems.push(_item);
            MessageService.showSuccess(showToast, 'AchatItems Created');
            setItem((prevState :any) => ({...prevState, achatItems: item.achatItems }));
        } else {
            const updatedItems = item.achatItems.map((item) => item.id === achatItems.id ? {...achatItems} : item);
            MessageService.showSuccess(showToast,'AchatItems Updated');
            setItem((prevState :any) => ({ ...prevState, achatItems: updatedItems}));
        }
        setAchatItems(new AchatItemDto());
    };

    const deleteAchatItems = (rowData: any) => {
        const updatedItems = item.achatItems.filter((val) => val !== rowData);
        setItem((prevState ) => ({...prevState,achatItems: updatedItems }));
        setAchatItems(new AchatItemDto());
        MessageService.showSuccess(showToast, 'AchatItem Deleted');
    };

    const editAchatItems = (rowData: any) => {
         setActiveTab(0);
         setAchatItems(rowData);

    };

    const onInputNumerChangeAchatItems = (e: any, name: string) => {
         const val = e.value || 0;
         setAchatItems((prevAchatItems) => ({...prevAchatItems, [name]: val, }));
    };
    const onDropdownChangeAchatItems = (e: any, field: string) => {
        setAchatItems((prevState) => ({ ...prevState, [field]: e.value}));
    };

    const onBooleanInputChangeAchatItems = (e: InputSwitchChangeEvent, name: string) => {
       const val = e.value;
       setAchatItems((prevItem) => ({ ...prevItem, [name]: val, }));
    };

    const onInputDateChangeAchatItems = (e: CalendarChangeEvent, name: string) => {
        const val = e.value || '';
        setAchatItems({ ...achatItems, [name]:val})
    };

    const onInputTextChangeAchatItems = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>, name: string) => {
        const val = (e.target && e.target.value) || '';
        setAchatItems({ ...achatItems, [name]:val})
    };




    const itemDialogFooter = ( <>
        <Button label={t("cancel")} icon="pi pi-times" text onClick={hideDialog} />
        <Button label={t("save")} icon="pi pi-check" onClick={saveItem} /> </>
    );

return(
        <Dialog visible={visible} style={{width: '70vw'}} header={t("achat.tabPan")} modal className="p-fluid" footer={itemDialogFooter} onHide={hideDialog} >
        <TabView activeIndex={activeIndex} onTabChange={onTabChange}>
            <TabPanel header={t("achat.tabPan")}>
                <div className="formgrid grid">
                    <div className="field col-6">
                        <label htmlFor="reference">{t("achat.reference")}</label>
                        <InputText id="reference" value={item.reference} onChange={(e) => onInputTextChange(e, 'reference')} required className={classNames({'p-invalid': submitted && !item.reference})} />
                        {submitted && !item.reference && <small className="p-invalid">Reference is required.</small>}
                    </div>
                    <div className="field col-6">
                        <label htmlFor="dateAchat">{t("achat.dateAchat")}</label>
                        <Calendar id="dateAchat" value={item.dateAchat} onChange={(e) => onInputDateChange(e, 'dateAchat')} dateFormat="dd/mm/yy"  showIcon={true} />
                    </div>
                    <div className="field col-6">
                        <label htmlFor="total">{t("achat.total")}</label>
                        <InputNumber id="total" value={item.total} onChange={(e) => onInputNumerChange(e, 'total')} />
                    </div>
                    <div className="field col-6">
                        <label htmlFor="totalPaye">{t("achat.totalPaye")}</label>
                        <InputNumber id="totalPaye" value={item.totalPaye} onChange={(e) => onInputNumerChange(e, 'totalPaye')} />
                    </div>
                    <div className="field col-6">
                        <label htmlFor="description">{t("achat.description")}</label>
                        <span className="p-float-label">
                        <InputTextarea id="description" value={item.description} onChange={(e) => onInputTextChange(e, 'description')} rows={5} cols={30}/>
                    </span>
                    </div>
                    <div className="field col-6">
                        <label htmlFor="client">{t("achat.client")}</label>
                        <Dropdown  id="clientDropdown"  value={item.client} options={clients} onChange={(e) => onDropdownChange(e, 'client')}   placeholder={t("achat.clientPlaceHolder")} filter filterPlaceholder={t("achat.clientPlaceHolderFilter")} optionLabel="nom" showClear/>
                    </div>
                </div>
            </TabPanel>
            <TabPanel header={t("achat.achatItems")}>
                <TabView activeIndex={activeTab} onTabChange={(e) => setActiveTab(e.index)}>
                    <TabPanel header={t("creation")}>
                        <div className="grid">
                            <div className="field col-6">
                                <label htmlFor="produit">{t("achatItem.produit")}</label>
                                <Dropdown id="produitDropdown" value={achatItems.produit} options={produits} onChange={(e) => onDropdownChangeAchatItems(e, 'produit')}    placeholder={t("achatItem.produitPlaceHolder")} filter filterPlaceholder={t("achatItem.produitPlaceHolderFilter")}  optionLabel="reference" showClear />
                             </div>
                            <div className="field col-6">
                                <label htmlFor="prixUnitaire">{t("achatItem.prixUnitaire")}</label>
                                <InputNumber id="prixUnitaire" value={achatItems.prixUnitaire}  onValueChange={(e) => onInputNumerChangeAchatItems(e, 'prixUnitaire')}/>
                            </div>
                            <div className="field col-6">
                                <label htmlFor="prixVente">{t("achatItem.prixVente")}</label>
                                <InputNumber id="prixVente" value={achatItems.prixVente}  onValueChange={(e) => onInputNumerChangeAchatItems(e, 'prixVente')}/>
                            </div>
                            <div className="field col-6">
                                <label htmlFor="quantite">{t("achatItem.quantite")}</label>
                                <InputNumber id="quantite" value={achatItems.quantite}  onValueChange={(e) => onInputNumerChangeAchatItems(e, 'quantite')}/>
                            </div>
                            <div className="field col-6">
                                <label htmlFor="quantiteAvoir">{t("achatItem.quantiteAvoir")}</label>
                                <InputNumber id="quantiteAvoir" value={achatItems.quantiteAvoir}  onValueChange={(e) => onInputNumerChangeAchatItems(e, 'quantiteAvoir')}/>
                            </div>
                            <div className="field col-6">
                                <label htmlFor="remise">{t("achatItem.remise")}</label>
                                <InputNumber id="remise" value={achatItems.remise}  onValueChange={(e) => onInputNumerChangeAchatItems(e, 'remise')}/>
                            </div>
                            <div className="field col-1">
                                <Button icon="pi pi-plus" label="OK" className="mt-4" onClick={addAchatItems} />
                            </div>
                        </div>
                    </TabPanel>
                    <TabPanel header={t("list")}>
                    <div className="card">
                    <DataTable value={item.achatItems} tableStyle={{minWidth: '50rem'}} dataKey="id">
                        <Column field="produit.reference" header={t("achatItem.produit")}></Column>
                        <Column field="prixUnitaire" header={t("achatItem.prixUnitaire")} ></Column>
                        <Column field="prixVente" header={t("achatItem.prixVente")} ></Column>
                        <Column field="quantite" header={t("achatItem.quantite")} ></Column>
                        <Column field="quantiteAvoir" header={t("achatItem.quantiteAvoir")} ></Column>
                        <Column field="remise" header={t("achatItem.remise")} ></Column>
                        <Column header={t("actions")} body={(rowData)=> (<div>
                        <Button icon="pi pi-times" rounded severity="warning" className="mr-2 p-button-danger" onClick={()=> deleteAchatItems(rowData)} />
                        <Button icon="pi pi-pencil" rounded severity="success" className="mr-2" onClick={()=> editAchatItems(rowData)} /> </div>)}></Column>
                    </DataTable>
                    </div>
                    </TabPanel>
                </TabView>
            </TabPanel>
        </TabView>
    </Dialog>
);
};
export default Create;

// frontend-angular/src/app/module/admin/view/stock/achat/create/achat-create-admin.component.ts
import {Component, OnInit, Input} from '@angular/core';

import { AbstractCreateController } from 'src/app/zynerator/controller/AbstractCreateController';

import {AchatAdminService} from 'src/app/controller/service/admin/stock/AchatAdmin.service';
import {AchatDto} from 'src/app/controller/model/stock/Achat.model';
import {AchatCriteria} from 'src/app/controller/criteria/stock/AchatCriteria.model';
import {ProduitDto} from 'src/app/controller/model/commun/Produit.model';
import {ProduitAdminService} from 'src/app/controller/service/admin/commun/ProduitAdmin.service';
import {AchatItemDto} from 'src/app/controller/model/stock/AchatItem.model';
import {AchatItemAdminService} from 'src/app/controller/service/admin/stock/AchatItemAdmin.service';
import {ClientDto} from 'src/app/controller/model/commun/Client.model';
import {ClientAdminService} from 'src/app/controller/service/admin/commun/ClientAdmin.service';
@Component({
  selector: 'app-achat-create-admin',
  templateUrl: './achat-create-admin.component.html'
})
export class AchatCreateAdminComponent extends AbstractCreateController<AchatDto, AchatCriteria, AchatAdminService>  implements OnInit {

    private _achatItemsElement = new AchatItemDto();


   private _validAchatReference = true;
    private _validClientCin = true;
    private _validClientNom = true;
    private _validAchatItemsProduit = true;
    private _validAchatItemsPrixUnitaire = true;
    private _validAchatItemsPrixVente = true;
    private _validAchatItemsQuantite = true;

    constructor( private achatService: AchatAdminService , private produitService: ProduitAdminService, private achatItemService: AchatItemAdminService, private clientService: ClientAdminService) {
        super(achatService);
    }

    ngOnInit(): void {
        this.achatItemsElement.produit = new ProduitDto();
        this.produitService.findAll().subscribe((data) => this.produits = data);
        this.client = new ClientDto();
        this.clientService.findAll().subscribe((data) => this.clients = data);
    }



    validateAchatItems(){
        this.errorMessages = new Array();
        this.validateAchatItemsProduit();
        this.validateAchatItemsPrixUnitaire();
        this.validateAchatItemsPrixVente();
        this.validateAchatItemsQuantite();
    }


    public setValidation(value: boolean){
        this.validAchatReference = value;
        this.validAchatItemsProduit = value;
        this.validAchatItemsPrixUnitaire = value;
        this.validAchatItemsPrixVente = value;
        this.validAchatItemsQuantite = value;
    }

    public addAchatItems() {
        if( this.item.achatItems == null )
            this.item.achatItems = new Array<AchatItemDto>();
       this.validateAchatItems();
       if (this.errorMessages.length === 0) {
              this.item.achatItems.push({... this.achatItemsElement});
              this.achatItemsElement = new AchatItemDto();
       }else{
            this.messageService.add({severity: 'error',summary: 'Erreurs',detail: 'Merci de corrigé les erreurs suivant : ' + this.errorMessages});
       }
    }


    public deleteachatItems(p: AchatItemDto) {
        this.item.achatItems.forEach((element, index) => {
            if (element === p) { this.item.achatItems.splice(index, 1); }
        });
    }

    public editachatItems(p: AchatItemDto) {
        this.achatItemsElement = {... p};
        this.activeTab = 0;
    }


    public validateForm(): void{
        this.errorMessages = new Array<string>();
        this.validateAchatReference();
    }

    public validateAchatReference(){
        if (this.stringUtilService.isEmpty(this.item.reference)) {
        this.errorMessages.push('Reference non valide');
        this.validAchatReference = false;
        } else {
            this.validAchatReference = true;
        }
    }

    public validateAchatItemsProduit(){
        if (this.achatItemsElement.produit == null) {
            this.errorMessages.push('Produit de la achatItem est  invalide');
            this.validAchatItemsProduit = false;
        } else {
            this.validAchatItemsProduit = true;
        }
    }
    public validateAchatItemsPrixUnitaire(){
        if (this.achatItemsElement.prixUnitaire == null) {
            this.errorMessages.push('PrixUnitaire de la achatItem est  invalide');
            this.validAchatItemsPrixUnitaire = false;
        } else {
            this.validAchatItemsPrixUnitaire = true;
        }
    }
    public validateAchatItemsPrixVente(){
        if (this.achatItemsElement.prixVente == null) {
            this.errorMessages.push('PrixVente de la achatItem est  invalide');
            this.validAchatItemsPrixVente = false;
        } else {
            this.validAchatItemsPrixVente = true;
        }
    }
    public validateAchatItemsQuantite(){
        if (this.achatItemsElement.quantite == null) {
            this.errorMessages.push('Quantite de la achatItem est  invalide');
            this.validAchatItemsQuantite = false;
        } else {
            this.validAchatItemsQuantite = true;
        }
    }


    get produit(): ProduitDto {
        return this.produitService.item;
    }
    set produit(value: ProduitDto) {
        this.produitService.item = value;
    }
    get produits(): Array<ProduitDto> {
        return this.produitService.items;
    }
    set produits(value: Array<ProduitDto>) {
        this.produitService.items = value;
    }
    get createProduitDialog(): boolean {
       return this.produitService.createDialog;
    }
    set createProduitDialog(value: boolean) {
        this.produitService.createDialog= value;
    }
    get client(): ClientDto {
        return this.clientService.item;
    }
    set client(value: ClientDto) {
        this.clientService.item = value;
    }
    get clients(): Array<ClientDto> {
        return this.clientService.items;
    }
    set clients(value: Array<ClientDto>) {
        this.clientService.items = value;
    }
    get createClientDialog(): boolean {
       return this.clientService.createDialog;
    }
    set createClientDialog(value: boolean) {
        this.clientService.createDialog= value;
    }



    get validAchatReference(): boolean {
        return this._validAchatReference;
    }

    set validAchatReference(value: boolean) {
         this._validAchatReference = value;
    }

    get validClientCin(): boolean {
        return this._validClientCin;
    }
    set validClientCin(value: boolean) {
        this._validClientCin = value;
    }
    get validClientNom(): boolean {
        return this._validClientNom;
    }
    set validClientNom(value: boolean) {
        this._validClientNom = value;
    }
    get validAchatItemsProduit(): boolean {
        return this._validAchatItemsProduit;
    }
    set validAchatItemsProduit(value: boolean) {
        this._validAchatItemsProduit = value;
    }
    get validAchatItemsPrixUnitaire(): boolean {
        return this._validAchatItemsPrixUnitaire;
    }
    set validAchatItemsPrixUnitaire(value: boolean) {
        this._validAchatItemsPrixUnitaire = value;
    }
    get validAchatItemsPrixVente(): boolean {
        return this._validAchatItemsPrixVente;
    }
    set validAchatItemsPrixVente(value: boolean) {
        this._validAchatItemsPrixVente = value;
    }
    get validAchatItemsQuantite(): boolean {
        return this._validAchatItemsQuantite;
    }
    set validAchatItemsQuantite(value: boolean) {
        this._validAchatItemsQuantite = value;
    }

    get achatItemsElement(): AchatItemDto {
        if( this._achatItemsElement == null )
            this._achatItemsElement = new AchatItemDto();
        return this._achatItemsElement;
    }

    set achatItemsElement(value: AchatItemDto) {
        this._achatItemsElement = value;
    }

}

        <p-dialog [(visible)]="createDialog" [style]="{width: '70vw'}" header="{{'achat.tabPan' | translate}}" [modal]="true" styleClass="p-fluid" [maximizable]="true" [draggable]="false" [resizable]="false">
            <ng-template pTemplate="content" >
                        <p-tabView>
                            <p-tabPanel header="{{'achat.tabPan' | translate}}">
                                <div class="grid">

                                                <div class="field col-12 md:col-6">
                                                    <label for="1">{{'achat.reference' | translate}}<span style="color: red;">*</span></label>
                                                    <input class="mb-2 mr-2" type="text" pInputText  placeholder="{{'achat.reference' | translate}}" id="1" [(ngModel)]="item.reference"
                                                            [ngClass]="{'ng-invalid ng-dirty' : !validAchatReference}"  />
                                                    <small class='p-error' *ngIf='!validAchatReference'>Reference est obligatoire.</small>
                                                </div>



                                                <div class="field col-12 md:col-6">
                                                    <label for="2">{{'achat.dateAchat' | translate}}</label>
                                                    <p-calendar appendTo="body" id="2"  [showTime]="true" [showSeconds]="false" placeholder="{{'achat.dateAchat' | translate}}"  [(ngModel)]="item.dateAchat"
                                                            dateFormat="{{dateFormat}}"  >
                                                    </p-calendar>
                                                    
                                                </div>

                                                <div class="field col-12 md:col-6">
                                                    <label for="3">{{'achat.total' | translate}}</label>
                                                    <p-inputNumber class="mb-2 mr-2" id="3" placeholder="{{'achat.total' | translate}}" [(ngModel)]="item.total"  >
                                                    </p-inputNumber>
                                                    
                                                </div>

                                                <div class="field col-12 md:col-6">
                                                    <label for="4">{{'achat.totalPaye' | translate}}</label>
                                                    <p-inputNumber class="mb-2 mr-2" id="4" placeholder="{{'achat.totalPaye' | translate}}" [(ngModel)]="item.totalPaye"  >
                                                    </p-inputNumber>
                                                    
                                                </div>

                                                <div class="field col-12 md:col-6">
                                                    <label for="5">{{'achat.description' | translate}}</label>
                                                    <textarea id="5" pInputTextarea rows="5" cols="30" placeholder="{{'achat.description' | translate}}"  [(ngModel)]="item.description"
                                                             ></textarea>
                                                    
                                                </div>

                                            <div class="field col-11 md:col-6">
                                                <label for="6">{{'achat.client' | translate}}</label>
                                                <p-dropdown  appendTo="body"  [options]="clients" [(ngModel)]="item.client" id="6" [filter]="true" filterMatchMode="contains"
                                                        [showClear]="true" optionLabel="nom" placeholder="{{'achat.client' | translate}}"  >
                                                </p-dropdown>
                                                
                                            </div>
                                </div>
                            </p-tabPanel>
                                    <p-tabPanel header="{{'achat.achatItems' | translate}}">
                                        <p-tabView [(activeIndex)]="activeTab">
                                            <p-tabPanel header="Création">
                                                    <div class="grid">
                                                                    <div class="field col-11 md:col-6">
                                                                        <label>Produit<span style="color: red;">*</span></label>
                                                                        <p-dropdown  appendTo="body"  [options]="produits" [(ngModel)]="achatItemsElement.produit"
                                                                                     id="1"  [filter]="true" filterMatchMode="contains" [showClear]="true" optionLabel="reference"
                                                                                     placeholder="Produit"  [ngClass]="{'ng-invalid ng-dirty' : !validAchatItemsProduit}" >
                                                                        </p-dropdown>
                                                                        <small class='p-error' *ngIf='!validAchatItemsProduit'>Produit est obligatoire.</small>
                                                                    </div>
                                                                    <div class="field col-12 md:col-6">
                                                                        <label for="2">Prix unitaire<span style="color: red;">*</span></label>
                                                                        <p-inputNumber class="mb-2 mr-2" id="prixUnitaire" placeholder="Prix unitaire"  [ngClass]="{'ng-invalid ng-dirty' : !validAchatItemsPrixUnitaire}" [(ngModel)]="achatItemsElement.prixUnitaire"></p-inputNumber>
                                                                        <small class='p-error' *ngIf='!validAchatItemsPrixUnitaire'>PrixUnitaire est obligatoire.</small>
                                                                    </div>
                                                                    <div class="field col-12 md:col-6">
                                                                        <label for="3">Prix vente<span style="color: red;">*</span></label>
                                                                        <p-inputNumber class="mb-2 mr-2" id="prixVente" placeholder="Prix vente"  [ngClass]="{'ng-invalid ng-dirty' : !validAchatItemsPrixVente}" [(ngModel)]="achatItemsElement.prixVente"></p-inputNumber>
                                                                        <small class='p-error' *ngIf='!validAchatItemsPrixVente'>PrixVente est obligatoire.</small>
                                                                    </div>
                                                                    <div class="field col-12 md:col-6">
                                                                        <label for="4">Quantite<span style="color: red;">*</span></label>
                                                                        <p-inputNumber class="mb-2 mr-2" id="quantite" placeholder="Quantite"  [ngClass]="{'ng-invalid ng-dirty' : !validAchatItemsQuantite}" [(ngModel)]="achatItemsElement.quantite"></p-inputNumber>
                                                                        <small class='p-error' *ngIf='!validAchatItemsQuantite'>Quantite est obligatoire.</small>
                                                                    </div>
                                                                    <div class="field col-12 md:col-6">
                                                                        <label for="5">Quantite avoir</label>
                                                                        <p-inputNumber class="mb-2 mr-2" id="quantiteAvoir" placeholder="Quantite avoir"  [(ngModel)]="achatItemsElement.quantiteAvoir"></p-inputNumber>
                                                                        
                                                                    </div>
                                                                    <div class="field col-12 md:col-6">
                                                                        <label for="6">Remise</label>
                                                                        <p-inputNumber class="mb-2 mr-2" id="remise" placeholder="Remise"  [(ngModel)]="achatItemsElement.remise"></p-inputNumber>
                                                                        
                                                                    </div>
                                                        <div class="field col-12 md:col-1">
                                                            <button pButton pRipple type="button" icon="pi pi-plus" class="mt-4" label="OK" (click)="addAchatItems()"></button>
                                                        </div>

                                                    </div>
                                            </p-tabPanel>
                                            <p-tabPanel header="Liste {{item.achatItems?.length > 0 ? '(' + item.achatItems?.length + ')' : ''}}">
                                                    <div class="card">
                                                        <p-table [value]="item.achatItems" [scrollable]="true" scrollHeight="200px">
                                                            <ng-template pTemplate="header">
                                                                <tr>
                                                                                <th>Produit</th>
                                                                                <th>Prix unitaire</th>
                                                                                <th>Prix vente</th>
                                                                                <th>Quantite</th>
                                                                                <th>Quantite avoir</th>
                                                                                <th>Remise</th>
                                                                    <th>Actions</th>
                                                                </tr>
                                                            </ng-template>
                                                            <ng-template pTemplate="body" let-p>
                                                                <tr>
                                                                            <td>{{p.produit?.reference}}</td>
                                                                                <td>{{p.prixUnitaire}}</td>
                                                                                <td>{{p.prixVente}}</td>
                                                                                <td>{{p.quantite}}</td>
                                                                                <td>{{p.quantiteAvoir}}</td>
                                                                                <td>{{p.remise}}</td>
                                                                    <td>
                                                                        <button (click)="deleteAchatItems(p)" pButton type="button" icon="pi pi-times"  class="p-button-rounded p-button-danger"></button>
                                                                        <button (click)="editAchatItems(p)" pButton type="button" icon="pi pi-pencil" class="p-button-rounded p-button-success mr-2"></button>
                                                                    </td>
                                                                </tr>
                                                            </ng-template>
                                                        </p-table>
                                                    </div>

                                            </p-tabPanel>
                                        </p-tabView>
                                    </p-tabPanel>


                        </p-tabView>

            </ng-template>

            <ng-template pTemplate="footer" >
                <div class="grid-step">
                        <div style="margin-left: auto;">
                            <button pButton pRipple  label="{{'validate' | translate}}"  icon="pi pi-check" style="margin:10px" (click)="save()"></button>
                        </div>
                        <div>
                            <button pButton pRipple  label="{{'cancel' | translate}}" icon="pi pi-times" class="p-button-outlined" (click)="hideCreateDialog()"></button>
                        </div>

                </div>
            </ng-template>



    </p-dialog>
