// frontend-angular/src/app/module/admin/view/stock/achat-item/view/achat-item-view-admin.component.ts
import {Component, OnInit} from '@angular/core';


import {AbstractViewController} from 'src/app/zynerator/controller/AbstractViewController';
import { environment } from 'src/environments/environment';

import {AchatItemAdminService} from 'src/app/controller/service/admin/stock/AchatItemAdmin.service';
import {AchatItemDto} from 'src/app/controller/model/stock/AchatItem.model';
import {AchatItemCriteria} from 'src/app/controller/criteria/stock/AchatItemCriteria.model';

import {ProduitDto} from 'src/app/controller/model/commun/Produit.model';
import {ProduitAdminService} from 'src/app/controller/service/admin/commun/ProduitAdmin.service';
import {AchatDto} from 'src/app/controller/model/stock/Achat.model';
import {AchatAdminService} from 'src/app/controller/service/admin/stock/AchatAdmin.service';
@Component({
  selector: 'app-achat-item-view-admin',
  templateUrl: './achat-item-view-admin.component.html'
})
export class AchatItemViewAdminComponent extends AbstractViewController<AchatItemDto, AchatItemCriteria, AchatItemAdminService> implements OnInit {


    constructor(private achatItemService: AchatItemAdminService, private produitService: ProduitAdminService, private achatService: AchatAdminService){
        super(achatItemService);
    }

    ngOnInit(): void {
    }


    get produit(): ProduitDto {
       return this.produitService.item;
    }
    set produit(value: ProduitDto) {
        this.produitService.item = value;
    }
    get produits(): Array<ProduitDto> {
       return this.produitService.items;
    }
    set produits(value: Array<ProduitDto>) {
        this.produitService.items = value;
    }
    get achat(): AchatDto {
       return this.achatService.item;
    }
    set achat(value: AchatDto) {
        this.achatService.item = value;
    }
    get achats(): Array<AchatDto> {
       return this.achatService.items;
    }
    set achats(value: Array<AchatDto>) {
        this.achatService.items = value;
    }


}


<p-dialog [(visible)]="viewDialog" [style]="{width: '70vw'}" header="{{'achatItem.tabPan' | translate}}" [modal]="true" styleClass="p-fluid">
    <ng-template pTemplate="content">
        <p-tabView>
            <p-tabPanel header="{{'achatItem.tabPan' | translate}}">
                <div class="grid">
                    <div class="field col-12 md:col-6">
                        <label for="1">{{'achatItem.produit' | translate}}</label>
                        <input class="mb-2 mr-2" type="text" pInputText [disabled]="true" placeholder="{{'achatItem.produit' | translate}}" autofocus  id="1" [(ngModel)]="item.produit.reference">
                    </div>
                    <div class="field col-12 md:col-6">
                        <label for="2">{{'achatItem.prixUnitaire' | translate}}</label>
                        <p-inputNumber class="mb-2 mr-2" id="2" [disabled]="true" placeholder="{{'achatItem.prixUnitaire' | translate}}" [(ngModel)]="item.prixUnitaire"></p-inputNumber>
                    </div>
                    <div class="field col-12 md:col-6">
                        <label for="3">{{'achatItem.prixVente' | translate}}</label>
                        <p-inputNumber class="mb-2 mr-2" id="3" [disabled]="true" placeholder="{{'achatItem.prixVente' | translate}}" [(ngModel)]="item.prixVente"></p-inputNumber>
                    </div>
                    <div class="field col-12 md:col-6">
                        <label for="4">{{'achatItem.quantite' | translate}}</label>
                        <p-inputNumber class="mb-2 mr-2" id="4" [disabled]="true" placeholder="{{'achatItem.quantite' | translate}}" [(ngModel)]="item.quantite"></p-inputNumber>
                    </div>
                    <div class="field col-12 md:col-6">
                        <label for="5">{{'achatItem.quantiteAvoir' | translate}}</label>
                        <p-inputNumber class="mb-2 mr-2" id="5" [disabled]="true" placeholder="{{'achatItem.quantiteAvoir' | translate}}" [(ngModel)]="item.quantiteAvoir"></p-inputNumber>
                    </div>
                    <div class="field col-12 md:col-6">
                        <label for="6">{{'achatItem.remise' | translate}}</label>
                        <p-inputNumber class="mb-2 mr-2" id="6" [disabled]="true" placeholder="{{'achatItem.remise' | translate}}" [(ngModel)]="item.remise"></p-inputNumber>
                    </div>
                    <div class="field col-12 md:col-6">
                        <label for="7">{{'achatItem.achat' | translate}}</label>
                        <input class="mb-2 mr-2" type="text" pInputText [disabled]="true" placeholder="{{'achatItem.achat' | translate}}" autofocus  id="7" [(ngModel)]="item.achat.reference">
                    </div>
                </div>
            </p-tabPanel>

        </p-tabView>

    </ng-template>

    <ng-template pTemplate="footer" >
        <div class="grid-footer">
            <div>
                <button pButton pRipple label="Annuler" icon="pi pi-times" class="p-button-outlined" (click)="hideViewDialog()"></button>
            </div>
        </div>
    </ng-template>
</p-dialog>

// frontend-react/app/component/admin/view/stock/achat-item/view/achat-item-view-admin.component.tsx
import {Column} from 'primereact/column';
import {TabPanel, TabView} from 'primereact/tabview';
import {DataTable} from 'primereact/datatable';
import {Dialog} from 'primereact/dialog';
import {InputNumber} from 'primereact/inputnumber';
import {InputText} from 'primereact/inputtext';
import {InputTextarea} from 'primereact/inputtextarea';
import React from 'react';
import {Calendar} from 'primereact/calendar';
import {InputSwitch} from 'primereact/inputswitch';
import {TFunction} from "i18next";
import useViewHook from "app/component/zyhook/useViewhook";

import  {AchatItemDto}  from 'app/controller/model/stock/AchatItem.model';

type AchatItemViewAdminType = {
    visible: boolean,
    onClose: () => void,
    selectedItem: AchatItemDto,
    t: TFunction
}

const View: React.FC<AchatItemViewAdminType> = ({visible,onClose,selectedItem, t}) => {

    const {
    onTabChange,
    hideDialog,
    itemDialogFooter,
    formateDate,
    parse,
    parseToIsoFormat,
    adaptDate,
    activeIndex
    } = useViewHook<AchatItemDto>({selectedItem, onClose})

        return(
<Dialog visible={visible} style={{width: '70vw'}} header={t("achatItem.tabPan")} modal className="p-fluid" footer={itemDialogFooter} onHide={hideDialog} >
<TabView activeIndex={activeIndex} onTabChange={onTabChange}>
<TabPanel header={t("achatItem.tabPan")}>
    <div className="formgrid grid">

                <div className="field col-6">
                    <label htmlFor="produit">{t("achatItem.produit")}</label>
                    <InputText  id="produitDropdown"  value={selectedItem?.produit?.reference}  disabled  />
                </div>
                <div className="field col-6">
                    <label htmlFor="prixUnitaire">{t("achatItem.prixUnitaire")}</label>
                    <InputNumber id="prixUnitaire" value={selectedItem.prixUnitaire} disabled/>
                </div>

                <div className="field col-6">
                    <label htmlFor="prixVente">{t("achatItem.prixVente")}</label>
                    <InputNumber id="prixVente" value={selectedItem.prixVente} disabled/>
                </div>

                <div className="field col-6">
                    <label htmlFor="quantite">{t("achatItem.quantite")}</label>
                    <InputNumber id="quantite" value={selectedItem.quantite} disabled/>
                </div>

                <div className="field col-6">
                    <label htmlFor="quantiteAvoir">{t("achatItem.quantiteAvoir")}</label>
                    <InputNumber id="quantiteAvoir" value={selectedItem.quantiteAvoir} disabled/>
                </div>

                <div className="field col-6">
                    <label htmlFor="remise">{t("achatItem.remise")}</label>
                    <InputNumber id="remise" value={selectedItem.remise} disabled/>
                </div>

                <div className="field col-6">
                    <label htmlFor="achat">{t("achatItem.achat")}</label>
                    <InputText  id="achatDropdown"  value={selectedItem?.achat?.reference}  disabled  />
                </div>
        </div>
</TabPanel>
</TabView>
</Dialog>
);
};
export default View;
