// frontend-next-v1/components/admin/view/commun/produit/view/produit-view-admin.component.tsx
import {Column} from 'primereact/column';
import {TabPanel, TabView} from 'primereact/tabview';
import {DataTable} from 'primereact/datatable';
import {Dialog} from 'primereact/dialog';
import {InputNumber} from 'primereact/inputnumber';
import {InputText} from 'primereact/inputtext';
import {InputTextarea} from 'primereact/inputtextarea';
import React from 'react';
import {Calendar} from 'primereact/calendar';
import {InputSwitch} from 'primereact/inputswitch';
import {TFunction} from "i18next";

import  {ProduitDto}  from '@/controller/model/commun/Produit.model';

import useViewHook from "@/utils/zyhook/useViewhook";

type ProduitViewAdminType = {
    visible: boolean,
    onClose: () => void,
    selectedItem: ProduitDto,
    t: TFunction
}

const View: React.FC<ProduitViewAdminType> = ({visible,onClose,selectedItem, t}) => {

    const {
    onTabChange,
    hideDialog,
    itemDialogFooter,
    formateDate,
    parse,
    parseToIsoFormat,
    adaptDate,
    activeIndex
    } = useViewHook<ProduitDto>({selectedItem, onClose})

        return(
<Dialog visible={visible} style={{width: '70vw'}} header={t("produit.tabPan")} modal className="p-fluid" footer={itemDialogFooter} onHide={hideDialog} >
<TabView activeIndex={activeIndex} onTabChange={onTabChange}>
<TabPanel header={t("produit.tabPan")}>
    <div className="formgrid grid">

            <div className="field col-6">
                <label htmlFor="reference">{t("produit.reference")}</label>
                <InputText id="reference" value={selectedItem?.reference} disabled   />
            </div>

            <div className="field col-6">
                <label htmlFor="libelle">{t("produit.libelle")}</label>
                <InputText id="libelle" value={selectedItem?.libelle} disabled   />
            </div>

            <div className="field col-6">
                <label htmlFor="barcode">{t("produit.barcode")}</label>
                <InputText id="barcode" value={selectedItem?.barcode} disabled   />
            </div>

            <div className="field col-6">
                <label htmlFor="discription">{t("produit.discription")}</label>
                <InputText id="discription" value={selectedItem?.discription} disabled   />
            </div>

                <div className="field col-6">
                    <label htmlFor="prixAchatMoyen">{t("produit.prixAchatMoyen")}</label>
                    <InputNumber id="prixAchatMoyen" value={selectedItem.prixAchatMoyen} disabled/>
                </div>

                <div className="field col-6">
                    <label htmlFor="quantite">{t("produit.quantite")}</label>
                    <InputNumber id="quantite" value={selectedItem.quantite} disabled/>
                </div>

                <div className="field col-6">
                    <label htmlFor="seuilAlert">{t("produit.seuilAlert")}</label>
                    <InputNumber id="seuilAlert" value={selectedItem.seuilAlert} disabled/>
                </div>

        </div>
</TabPanel>
</TabView>
</Dialog>
);
};
export default View;

// frontend-angular/src/app/module/admin/view/commun/produit/view/produit-view-admin.component.ts
import {Component, OnInit} from '@angular/core';


import {AbstractViewController} from 'src/app/zynerator/controller/AbstractViewController';
import { environment } from 'src/environments/environment';

import {ProduitAdminService} from 'src/app/controller/service/admin/commun/ProduitAdmin.service';
import {ProduitDto} from 'src/app/controller/model/commun/Produit.model';
import {ProduitCriteria} from 'src/app/controller/criteria/commun/ProduitCriteria.model';

@Component({
  selector: 'app-produit-view-admin',
  templateUrl: './produit-view-admin.component.html'
})
export class ProduitViewAdminComponent extends AbstractViewController<ProduitDto, ProduitCriteria, ProduitAdminService> implements OnInit {


    constructor(private produitService: ProduitAdminService){
        super(produitService);
    }

    ngOnInit(): void {
    }




}


<p-dialog [(visible)]="viewDialog" [style]="{width: '70vw'}" header="{{'produit.tabPan' | translate}}" [modal]="true" styleClass="p-fluid">
    <ng-template pTemplate="content">
        <p-tabView>
            <p-tabPanel header="{{'produit.tabPan' | translate}}">
                <div class="grid">
                    <div class="field col-12 md:col-6">
                        <label for="1">{{'produit.reference' | translate}}</label>
                        <input class="mb-2 mr-2" type="text" pInputText [disabled]="true" placeholder="{{'produit.reference' | translate}}" autofocus  id="1" [(ngModel)]="item.reference">
                    </div>
                    <div class="field col-12 md:col-6">
                        <label for="2">{{'produit.libelle' | translate}}</label>
                        <input class="mb-2 mr-2" type="text" pInputText [disabled]="true" placeholder="{{'produit.libelle' | translate}}" autofocus  id="2" [(ngModel)]="item.libelle">
                    </div>
                    <div class="field col-12 md:col-6">
                        <label for="3">{{'produit.barcode' | translate}}</label>
                        <input class="mb-2 mr-2" type="text" pInputText [disabled]="true" placeholder="{{'produit.barcode' | translate}}" autofocus  id="3" [(ngModel)]="item.barcode">
                    </div>
                    <div class="field col-12 md:col-6">
                        <label for="4">{{'produit.discription' | translate}}</label>
                        <textarea id="4" pInputTextarea rows="5" cols="30" [disabled]="true" placeholder="{{'produit.discription' | translate}}"  [(ngModel)]="item.discription"></textarea>
                    </div>
                    <div class="field col-12 md:col-6">
                        <label for="5">{{'produit.prixAchatMoyen' | translate}}</label>
                        <p-inputNumber class="mb-2 mr-2" id="5" [disabled]="true" placeholder="{{'produit.prixAchatMoyen' | translate}}" [(ngModel)]="item.prixAchatMoyen"></p-inputNumber>
                    </div>
                    <div class="field col-12 md:col-6">
                        <label for="6">{{'produit.quantite' | translate}}</label>
                        <p-inputNumber class="mb-2 mr-2" id="6" [disabled]="true" placeholder="{{'produit.quantite' | translate}}" [(ngModel)]="item.quantite"></p-inputNumber>
                    </div>
                    <div class="field col-12 md:col-6">
                        <label for="7">{{'produit.seuilAlert' | translate}}</label>
                        <p-inputNumber class="mb-2 mr-2" id="7" [disabled]="true" placeholder="{{'produit.seuilAlert' | translate}}" [(ngModel)]="item.seuilAlert"></p-inputNumber>
                    </div>
                </div>
            </p-tabPanel>

        </p-tabView>

    </ng-template>

    <ng-template pTemplate="footer" >
        <div class="grid-footer">
            <div>
                <button pButton pRipple label="Annuler" icon="pi pi-times" class="p-button-outlined" (click)="hideViewDialog()"></button>
            </div>
        </div>
    </ng-template>
</p-dialog>
