// frontend-angular/src/app/module/admin/view/commun/client/create/client-create-admin.component.ts
import {Component, OnInit, Input} from '@angular/core';

import { AbstractCreateController } from 'src/app/zynerator/controller/AbstractCreateController';

import {ClientAdminService} from 'src/app/controller/service/admin/commun/ClientAdmin.service';
import {ClientDto} from 'src/app/controller/model/commun/Client.model';
import {ClientCriteria} from 'src/app/controller/criteria/commun/ClientCriteria.model';
@Component({
  selector: 'app-client-create-admin',
  templateUrl: './client-create-admin.component.html'
})
export class ClientCreateAdminComponent extends AbstractCreateController<ClientDto, ClientCriteria, ClientAdminService>  implements OnInit {



   private _validClientCin = true;
   private _validClientNom = true;

    constructor( private clientService: ClientAdminService ) {
        super(clientService);
    }

    ngOnInit(): void {
    }

    public save(): void {
        super.save();
    }




    public setValidation(value: boolean){
        this.validClientCin = value;
        this.validClientNom = value;
    }



    public validateForm(): void{
        this.errorMessages = new Array<string>();
        this.validateClientCin();
        this.validateClientNom();
    }

    public validateClientCin(){
        if (this.stringUtilService.isEmpty(this.item.cin)) {
        this.errorMessages.push('Cin non valide');
        this.validClientCin = false;
        } else {
            this.validClientCin = true;
        }
    }
    public validateClientNom(){
        if (this.stringUtilService.isEmpty(this.item.nom)) {
        this.errorMessages.push('Nom non valide');
        this.validClientNom = false;
        } else {
            this.validClientNom = true;
        }
    }






    get validClientCin(): boolean {
        return this._validClientCin;
    }

    set validClientCin(value: boolean) {
         this._validClientCin = value;
    }
    get validClientNom(): boolean {
        return this._validClientNom;
    }

    set validClientNom(value: boolean) {
         this._validClientNom = value;
    }



}

        <p-dialog [(visible)]="createDialog" [style]="{width: '70vw'}" header="{{'client.tabPan' | translate}}" [modal]="true" styleClass="p-fluid" [maximizable]="true" [draggable]="false" [resizable]="false">
            <ng-template pTemplate="content" >
                        <p-tabView>
                            <p-tabPanel header="{{'client.tabPan' | translate}}">
                                <div class="grid">

                                                <div class="field col-12 md:col-6">
                                                    <label for="1">{{'client.cin' | translate}}<span style="color: red;">*</span></label>
                                                    <input class="mb-2 mr-2" type="text" pInputText  placeholder="{{'client.cin' | translate}}" id="1" [(ngModel)]="item.cin"
                                                            [ngClass]="{'ng-invalid ng-dirty' : !validClientCin}"  />
                                                    <small class='p-error' *ngIf='!validClientCin'>Cin est obligatoire.</small>
                                                </div>



                                                <div class="field col-12 md:col-6">
                                                    <label for="2">{{'client.nom' | translate}}<span style="color: red;">*</span></label>
                                                    <input class="mb-2 mr-2" type="text" pInputText  placeholder="{{'client.nom' | translate}}" id="2" [(ngModel)]="item.nom"
                                                            [ngClass]="{'ng-invalid ng-dirty' : !validClientNom}"  />
                                                    <small class='p-error' *ngIf='!validClientNom'>Nom est obligatoire.</small>
                                                </div>



                                                <div class="field col-12 md:col-6">
                                                    <label for="3">{{'client.tel' | translate}}</label>
                                                    <p-inputNumber class="mb-2 mr-2" id="3" placeholder="{{'client.tel' | translate}}" [(ngModel)]="item.tel"  >
                                                    </p-inputNumber>
                                                    
                                                </div>

                                                <div class="field col-12 md:col-6">
                                                    <label for="4">{{'client.email' | translate}}</label>
                                                    <input class="mb-2 mr-2" type="text" pInputText  placeholder="{{'client.email' | translate}}" id="4" [(ngModel)]="item.email"
                                                             />
                                                    
                                                </div>



                                                <div class="field col-12 md:col-6">
                                                    <label for="5">{{'client.adresse' | translate}}</label>
                                                    <p-inputNumber class="mb-2 mr-2" id="5" placeholder="{{'client.adresse' | translate}}" [(ngModel)]="item.adresse"  >
                                                    </p-inputNumber>
                                                    
                                                </div>

                                                <div class="field col-12 md:col-6">
                                                    <label for="6">{{'client.description' | translate}}</label>
                                                    <textarea id="6" pInputTextarea rows="5" cols="30" placeholder="{{'client.description' | translate}}"  [(ngModel)]="item.description"
                                                             ></textarea>
                                                    
                                                </div>

                                                <div class="field col-12 md:col-6">
                                                    <label for="7">{{'client.creance' | translate}}</label>
                                                    <p-inputNumber class="mb-2 mr-2" id="7" placeholder="{{'client.creance' | translate}}" [(ngModel)]="item.creance"  >
                                                    </p-inputNumber>
                                                    
                                                </div>

                                </div>
                            </p-tabPanel>

                        </p-tabView>

            </ng-template>

            <ng-template pTemplate="footer" >
                <div class="grid-step">
                        <div style="margin-left: auto;">
                            <button pButton pRipple  label="{{'validate' | translate}}"  icon="pi pi-check" style="margin:10px" (click)="save()"></button>
                        </div>
                        <div>
                            <button pButton pRipple  label="{{'cancel' | translate}}" icon="pi pi-times" class="p-button-outlined" (click)="hideCreateDialog()"></button>
                        </div>

                </div>
            </ng-template>



    </p-dialog>

// error-ng-build-list-hook/frontend-react-v2/app/component/admin/view/commun/client/create/client-create-admin.component.tsx
import {Button} from 'primereact/button';
import {Column} from 'primereact/column';
import {TabView, TabPanel} from 'primereact/tabview';
import {Dialog} from 'primereact/dialog';
import {InputNumber, InputNumberChangeEvent} from 'primereact/inputnumber';
import {InputText} from 'primereact/inputtext';
import {classNames} from 'primereact/utils';
import { InputTextarea } from 'primereact/inputtextarea';
import React, {useEffect, useState} from 'react';
import {Calendar, CalendarChangeEvent} from 'primereact/calendar';
import { format } from 'date-fns';
import {InputSwitch, InputSwitchChangeEvent} from 'primereact/inputswitch';
import {Dropdown, DropdownChangeEvent} from 'primereact/dropdown';
import {MultiSelect, MultiSelectChangeEvent} from 'primereact/multiselect';
import {MessageService} from 'app/zynerator/service/MessageService';

import {ClientAdminService} from 'app/controller/service/admin/commun/ClientAdminService.service';
import  {ClientDto}  from 'app/controller/model/commun/Client.model';
import {ClientCriteria} from "app/controller/criteria/commun/ClientCriteria.model";

import {TFunction} from "i18next";
import {Toast} from "primereact/toast";
import useCreateHook from "app/component/zyhook/useCreate.hook";



type ClientCreateAdminType = {
    visible: boolean,
    onClose: () => void,
    add: (item: ClientDto) => void,
    showToast: React.Ref<Toast>,
    list: ClientDto[],
    service: ClientAdminService,
    t: TFunction
}
const Create: React.FC<ClientCreateAdminType> = ({visible, onClose, add, showToast, list, service, t}) => {


    const isFormValid = () => {
    let errorMessages = new Array<string>();
                if(item.cin == '')
                    errorMessages.push("cin is required")
                if(item.nom == '')
                    errorMessages.push("nom is required")
        return errorMessages.length == 0 ;
    }
    const emptyItem = new ClientDto();
        const {
            item,
            setItem,
            submitted,
            setSubmitted,
            activeIndex,
            setActiveIndex,
            activeTab,
            setActiveTab,
            onInputTextChange,
            onInputDateChange,
            onInputNumerChange,
            onMultiSelectChange,
            onBooleanInputChange,
            onTabChange,
            onDropdownChange,
            hideDialog,
            saveItem,
            formateDate
        } = useCreateHook<ClientDto, ClientCriteria>({list, emptyItem, onClose, add, showToast,service, isFormValid})


    useEffect(() => {
    }, []);








    const itemDialogFooter = ( <>
        <Button label={t("cancel")} icon="pi pi-times" text onClick={hideDialog} />
        <Button label={t("save")} icon="pi pi-check" onClick={saveItem} /> </>
    );

return(
        <Dialog visible={visible} style={{width: '70vw'}} header={t("client.tabPan")} modal className="p-fluid" footer={itemDialogFooter} onHide={hideDialog} >
        <TabView activeIndex={activeIndex} onTabChange={onTabChange}>
            <TabPanel header={t("client.tabPan")}>
                <div className="formgrid grid">
                    <div className="field col-6">
                        <label htmlFor="cin">{t("client.cin")}</label>
                        <InputText id="cin" value={item.cin} onChange={(e) => onInputTextChange(e, 'cin')} required className={classNames({'p-invalid': submitted && !item.cin})} />
                        {submitted && !item.cin && <small className="p-invalid">Cin is required.</small>}
                    </div>
                    <div className="field col-6">
                        <label htmlFor="nom">{t("client.nom")}</label>
                        <InputText id="nom" value={item.nom} onChange={(e) => onInputTextChange(e, 'nom')} required className={classNames({'p-invalid': submitted && !item.nom})} />
                        {submitted && !item.nom && <small className="p-invalid">Nom is required.</small>}
                    </div>
                    <div className="field col-6">
                        <label htmlFor="tel">{t("client.tel")}</label>
                        <InputText id="tel" value={item.tel} onChange={(e) => onInputTextChange(e, 'tel')} required className={classNames({'p-invalid': submitted && !item.tel})} />
                        {submitted && !item.tel && <small className="p-invalid">Tel is required.</small>}
                    </div>
                    <div className="field col-6">
                        <label htmlFor="email">{t("client.email")}</label>
                        <InputText id="email" value={item.email} onChange={(e) => onInputTextChange(e, 'email')} required className={classNames({'p-invalid': submitted && !item.email})} />
                        {submitted && !item.email && <small className="p-invalid">Email is required.</small>}
                    </div>
                    <div className="field col-6">
                        <label htmlFor="adresse">{t("client.adresse")}</label>
                        <InputText id="adresse" value={item.adresse} onChange={(e) => onInputTextChange(e, 'adresse')} required className={classNames({'p-invalid': submitted && !item.adresse})} />
                        {submitted && !item.adresse && <small className="p-invalid">Adresse is required.</small>}
                    </div>
                    <div className="field col-6">
                        <label htmlFor="description">{t("client.description")}</label>
                        <span className="p-float-label">
                        <InputTextarea id="description" value={item.description} onChange={(e) => onInputTextChange(e, 'description')} rows={5} cols={30}/>
                    </span>
                    </div>
                    <div className="field col-6">
                        <label htmlFor="creance">{t("client.creance")}</label>
                        <InputNumber id="creance" value={item.creance} onChange={(e) => onInputNumerChange(e, 'creance')} />
                    </div>
                </div>
            </TabPanel>
        </TabView>
    </Dialog>
);
};
export default Create;
