// frontend-angular/src/app/module/admin/view/stock/achat-item/edit/achat-item-edit-admin.component.ts
import {Component, OnInit, Input} from '@angular/core';


import {AbstractEditController} from 'src/app/zynerator/controller/AbstractEditController';

import {AchatItemAdminService} from 'src/app/controller/service/admin/stock/AchatItemAdmin.service';
import {AchatItemDto} from 'src/app/controller/model/stock/AchatItem.model';
import {AchatItemCriteria} from 'src/app/controller/criteria/stock/AchatItemCriteria.model';


import {ProduitDto} from 'src/app/controller/model/commun/Produit.model';
import {ProduitAdminService} from 'src/app/controller/service/admin/commun/ProduitAdmin.service';
import {AchatDto} from 'src/app/controller/model/stock/Achat.model';
import {AchatAdminService} from 'src/app/controller/service/admin/stock/AchatAdmin.service';

@Component({
  selector: 'app-achat-item-edit-admin',
  templateUrl: './achat-item-edit-admin.component.html'
})
export class AchatItemEditAdminComponent extends AbstractEditController<AchatItemDto, AchatItemCriteria, AchatItemAdminService>   implements OnInit {


    private _validAchatItemProduit = true;
    private _validAchatItemPrixUnitaire = true;
    private _validAchatItemPrixVente = true;
    private _validAchatItemQuantite = true;

    private _validProduitReference = true;
    private _validAchatReference = true;



    constructor( private achatItemService: AchatItemAdminService , private produitService: ProduitAdminService, private achatService: AchatAdminService) {
        super(achatItemService);
    }

    ngOnInit(): void {
        this.produit = new ProduitDto();
        this.produitService.findAll().subscribe((data) => this.produits = data);
        this.achat = new AchatDto();
        this.achatService.findAll().subscribe((data) => this.achats = data);
    }


    public setValidation(value: boolean){
        this.validAchatItemProduit = value;
        this.validAchatItemPrixUnitaire = value;
        this.validAchatItemPrixVente = value;
        this.validAchatItemQuantite = value;
        }
    public validateForm(): void{
        this.errorMessages = new Array<string>();
        this.validateAchatItemProduit();
        this.validateAchatItemPrixUnitaire();
        this.validateAchatItemPrixVente();
        this.validateAchatItemQuantite();
    }
    public validateAchatItemProduit(){
        if (this.stringUtilService.isEmpty(this.item.produit)) {
            this.errorMessages.push('Produit non valide');
            this.validAchatItemProduit = false;
        } else {
            this.validAchatItemProduit = true;
        }
    }
    public validateAchatItemPrixUnitaire(){
        if (this.stringUtilService.isEmpty(this.item.prixUnitaire)) {
            this.errorMessages.push('Prix unitaire non valide');
            this.validAchatItemPrixUnitaire = false;
        } else {
            this.validAchatItemPrixUnitaire = true;
        }
    }
    public validateAchatItemPrixVente(){
        if (this.stringUtilService.isEmpty(this.item.prixVente)) {
            this.errorMessages.push('Prix vente non valide');
            this.validAchatItemPrixVente = false;
        } else {
            this.validAchatItemPrixVente = true;
        }
    }
    public validateAchatItemQuantite(){
        if (this.stringUtilService.isEmpty(this.item.quantite)) {
            this.errorMessages.push('Quantite non valide');
            this.validAchatItemQuantite = false;
        } else {
            this.validAchatItemQuantite = true;
        }
    }



   public async openCreateAchat(achat: string) {
        const isPermistted = await this.roleService.isPermitted('Achat', 'edit');
        if (isPermistted) {
             this.achat = new AchatDto();
             this.createAchatDialog = true;
        }else {
             this.messageService.add({
                severity: 'error', summary: 'erreur', detail: 'problème de permission'
            });
        }
    }

   get produit(): ProduitDto {
       return this.produitService.item;
   }
  set produit(value: ProduitDto) {
        this.produitService.item = value;
   }
   get produits(): Array<ProduitDto> {
        return this.produitService.items;
   }
   set produits(value: Array<ProduitDto>) {
        this.produitService.items = value;
   }
   get createProduitDialog(): boolean {
       return this.produitService.createDialog;
   }
  set createProduitDialog(value: boolean) {
       this.produitService.createDialog= value;
   }
   get achat(): AchatDto {
       return this.achatService.item;
   }
  set achat(value: AchatDto) {
        this.achatService.item = value;
   }
   get achats(): Array<AchatDto> {
        return this.achatService.items;
   }
   set achats(value: Array<AchatDto>) {
        this.achatService.items = value;
   }
   get createAchatDialog(): boolean {
       return this.achatService.createDialog;
   }
  set createAchatDialog(value: boolean) {
       this.achatService.createDialog= value;
   }


    get validAchatItemProduit(): boolean {
        return this._validAchatItemProduit;
    }
    set validAchatItemProduit(value: boolean) {
        this._validAchatItemProduit = value;
    }
    get validAchatItemPrixUnitaire(): boolean {
        return this._validAchatItemPrixUnitaire;
    }
    set validAchatItemPrixUnitaire(value: boolean) {
        this._validAchatItemPrixUnitaire = value;
    }
    get validAchatItemPrixVente(): boolean {
        return this._validAchatItemPrixVente;
    }
    set validAchatItemPrixVente(value: boolean) {
        this._validAchatItemPrixVente = value;
    }
    get validAchatItemQuantite(): boolean {
        return this._validAchatItemQuantite;
    }
    set validAchatItemQuantite(value: boolean) {
        this._validAchatItemQuantite = value;
    }

    get validProduitReference(): boolean {
        return this._validProduitReference;
    }
    set validProduitReference(value: boolean) {
        this._validProduitReference = value;
    }
    get validAchatReference(): boolean {
        return this._validAchatReference;
    }
    set validAchatReference(value: boolean) {
        this._validAchatReference = value;
    }
}

        <p-dialog [(visible)]="editDialog" [style]="{width: '70vw'}" header="{{'achatItem.tabPan' | translate}}" [modal]="true" styleClass="p-fluid" [maximizable]="true" [draggable]="false" [resizable]="false">
            <ng-template pTemplate="content" >
                <p-tabView>
                    <p-tabPanel header="{{'achatItem.tabPan' | translate}}">
                        <div class="grid">

                                    <div class="field col-11 md:col-6">
                                        <label for="1">{{'achatItem.produit' | translate}}<span style="color: red;">*</span></label>
                                        <p-dropdown  appendTo="body"  [options]="produits" [(ngModel)]="item.produit" id="1" [filter]="true" filterMatchMode="contains"
                                                [showClear]="true" optionLabel="reference" placeholder="{{'achatItem.produit' | translate}}" [ngClass]="{'ng-invalid ng-dirty' : !validAchatItemProduit}"  >
                                        </p-dropdown>
                                        <small class='p-error' *ngIf='!validAchatItemProduit'>Produit est obligatoire.</small>
                                    </div>
                                        <div class="field col-12 md:col-6">
                                            <label for="2">{{'achatItem.prixUnitaire' | translate}}<span style="color: red;">*</span></label>
                                            <p-inputNumber class="mb-2 mr-2" id="2" placeholder="{{'achatItem.prixUnitaire' | translate}}" [(ngModel)]="item.prixUnitaire" [ngClass]="{'ng-invalid ng-dirty' : !validAchatItemPrixUnitaire}"  >
                                            </p-inputNumber>
                                            <small class='p-error' *ngIf='!validAchatItemPrixUnitaire'>PrixUnitaire est obligatoire.</small>
                                        </div>

                                        <div class="field col-12 md:col-6">
                                            <label for="3">{{'achatItem.prixVente' | translate}}<span style="color: red;">*</span></label>
                                            <p-inputNumber class="mb-2 mr-2" id="3" placeholder="{{'achatItem.prixVente' | translate}}" [(ngModel)]="item.prixVente" [ngClass]="{'ng-invalid ng-dirty' : !validAchatItemPrixVente}"  >
                                            </p-inputNumber>
                                            <small class='p-error' *ngIf='!validAchatItemPrixVente'>PrixVente est obligatoire.</small>
                                        </div>

                                        <div class="field col-12 md:col-6">
                                            <label for="4">{{'achatItem.quantite' | translate}}<span style="color: red;">*</span></label>
                                            <p-inputNumber class="mb-2 mr-2" id="4" placeholder="{{'achatItem.quantite' | translate}}" [(ngModel)]="item.quantite" [ngClass]="{'ng-invalid ng-dirty' : !validAchatItemQuantite}"  >
                                            </p-inputNumber>
                                            <small class='p-error' *ngIf='!validAchatItemQuantite'>Quantite est obligatoire.</small>
                                        </div>

                                        <div class="field col-12 md:col-6">
                                            <label for="5">{{'achatItem.quantiteAvoir' | translate}}</label>
                                            <p-inputNumber class="mb-2 mr-2" id="5" placeholder="{{'achatItem.quantiteAvoir' | translate}}" [(ngModel)]="item.quantiteAvoir"  >
                                            </p-inputNumber>
                                            
                                        </div>

                                        <div class="field col-12 md:col-6">
                                            <label for="6">{{'achatItem.remise' | translate}}</label>
                                            <p-inputNumber class="mb-2 mr-2" id="6" placeholder="{{'achatItem.remise' | translate}}" [(ngModel)]="item.remise"  >
                                            </p-inputNumber>
                                            
                                        </div>

                                    <div class="field col-11 md:col-5">
                                        <label for="7">{{'achatItem.achat' | translate}}</label>
                                        <p-dropdown  appendTo="body"  [options]="achats" [(ngModel)]="item.achat" id="7" [filter]="true" filterMatchMode="contains"
                                                [showClear]="true" optionLabel="reference" placeholder="{{'achatItem.achat' | translate}}"  >
                                        </p-dropdown>
                                        
                                    </div>
                                        <div class="col-1">
                                            <label></label>
                                            <button pButton pRipple type="button" icon="pi pi-plus" (click)="openCreateAchat('Achat')" class="p-button-success one-colonne-btn-success-align"></button>
                                        </div>
                        </div>
                    </p-tabPanel>

                </p-tabView>
            </ng-template>

            <ng-template pTemplate="footer" >
                <div class="grid-footer">
                        <div>
                            <button pButton pRipple label="Annuler" icon="pi pi-times" class="p-button-outlined" (click)="hideEditDialog()"></button>
                        </div>
                    <div>
                        <button pButton pRipple label="Valider" icon="pi pi-check" style="margin:10px" (click)="edit()"></button>
                    </div>
                </div>
            </ng-template>

                    <app-achat-create-admin></app-achat-create-admin>


    </p-dialog>

// error-ng-build-list-hook/frontend/app/component/admin/view/stock/achat-item/edit/achat-item-edit-admin.component.tsx
import {Button} from 'primereact/button';
import {Column} from 'primereact/column';
import {Dropdown, DropdownChangeEvent} from 'primereact/dropdown';
import {TabView, TabPanel} from 'primereact/tabview';
import {Dialog} from 'primereact/dialog';
import {InputNumber, InputNumberChangeEvent} from 'primereact/inputnumber';
import {InputText} from 'primereact/inputtext';
import {classNames} from 'primereact/utils';
import { InputTextarea } from 'primereact/inputtextarea';
import React, {useEffect, useState} from 'react';
import {Calendar, CalendarChangeEvent} from 'primereact/calendar';
import { format } from 'date-fns';
import { parse } from 'date-fns';
import { InputSwitch } from 'primereact/inputswitch';
import {MultiSelect, MultiSelectChangeEvent} from 'primereact/multiselect';

import {MessageService} from 'app/zynerator/service/MessageService';



import {AchatItemAdminService} from 'app/controller/service/admin/stock/AchatItemAdminService.service';
import  {AchatItemDto}  from 'app/controller/model/stock/AchatItem.model';
import {AchatItemCriteria} from "app/controller/criteria/stock/AchatItemCriteria.model";

import {TFunction} from "i18next";
import {Toast} from "primereact/toast";

import {AchatDto} from 'app/controller/model/stock/Achat.model';
import {AchatAdminService} from 'app/controller/service/admin/stock/AchatAdminService.service';
import {ProduitDto} from 'app/controller/model/commun/Produit.model';
import {ProduitAdminService} from 'app/controller/service/admin/commun/ProduitAdminService.service';
import useEditHook from "app/component/zyhook/useEdit.hook";


type AchatItemEditAdminType = {
    visible: boolean,
    onClose: () => void,
    showToast: React.Ref<Toast>,
    selectedItem: AchatItemDto
    update: (item: AchatItemDto) => void,
    list: AchatItemDto[],
    service: AchatItemAdminService,
    t: TFunction
}
const Edit: React.FC<AchatItemEditAdminType> = ({visible, onClose, showToast, selectedItem, update, list, service, t}) => {


    const isFormValid = () => {
    let errorMessages = new Array<string>();
        if(item.produit == null)
            errorMessages.push("produit is required")
        if(item.prixUnitaire == null)
            errorMessages.push("prixUnitaire is required")
        if(item.prixVente == null)
            errorMessages.push("prixVente is required")
        if(item.quantite == null)
            errorMessages.push("quantite is required")
        return errorMessages.length == 0 ;
    }
    const emptyItem = new AchatItemDto();


    const {
        item,
        setItem,
        submitted,
        setSubmitted,
        activeIndex,
        setActiveIndex,
        activeTab,
        setActiveTab,
        onInputTextChange,
        onInputDateChange,
        onInputNumerChange,
        onMultiSelectChange,
        onBooleanInputChange,
        onDropdownChange,
        onTabChange,
        hideDialog,
        editItem,
        formateDate,
        parseToIsoFormat,
        adaptDate
        } = useEditHook<AchatItemDto, AchatItemCriteria>({list, selectedItem, onClose, update, showToast,service, t, isFormValid})

    const [produits, setProduits] = useState<ProduitDto[]>([]);
    const [achats, setAchats] = useState<AchatDto[]>([]);


    const achatAdminService = new AchatAdminService();
    const produitAdminService = new ProduitAdminService();
    useEffect(() => {
    produitAdminService.getList().then(({data}) => setProduits(data)).catch(error => console.log(error));
    achatAdminService.getList().then(({data}) => setAchats(data)).catch(error => console.log(error));


        }, []);







    const itemDialogFooter = ( <>
        <Button label="Cancel" icon="pi pi-times" text onClick={hideDialog} />
        <Button label="Save" icon="pi pi-check" onClick={editItem} /> </>
    );



    return(
    <Dialog visible={visible} style={{width: '70vw'}} header={t("achatItem.tabPan")} modal className="p-fluid" footer={itemDialogFooter} onHide={hideDialog}>
        <TabView activeIndex={activeIndex} onTabChange={onTabChange}>
            <TabPanel header={t("achatItem.tabPan")}>
                <div className="formgrid grid">
                    <div className="field col-6">
                        <label htmlFor="produit">{t("achatItem.produit")}</label>
                        <Dropdown  id="produitDropdown"  value={item ? item.produit : ''} options={produits} onChange={(e) => onDropdownChange(e, 'produit')}   placeholder="Sélectionnez un produit" filter filterPlaceholder="Rechercher un produit" optionLabel="reference" showClear />
                    </div>
                    <div className="field col-6">
                        <label htmlFor="prixUnitaire">{t("achatItem.prixUnitaire")}</label>
                        <InputNumber id="prixUnitaire" value={item ? item.prixUnitaire : 0} onChange={(e) => onInputNumerChange(e, 'prixUnitaire')}/>
                    </div>
                    <div className="field col-6">
                        <label htmlFor="prixVente">{t("achatItem.prixVente")}</label>
                        <InputNumber id="prixVente" value={item ? item.prixVente : 0} onChange={(e) => onInputNumerChange(e, 'prixVente')}/>
                    </div>
                    <div className="field col-6">
                        <label htmlFor="quantite">{t("achatItem.quantite")}</label>
                        <InputNumber id="quantite" value={item ? item.quantite : 0} onChange={(e) => onInputNumerChange(e, 'quantite')}/>
                    </div>
                    <div className="field col-6">
                        <label htmlFor="quantiteAvoir">{t("achatItem.quantiteAvoir")}</label>
                        <InputNumber id="quantiteAvoir" value={item ? item.quantiteAvoir : 0} onChange={(e) => onInputNumerChange(e, 'quantiteAvoir')}/>
                    </div>
                    <div className="field col-6">
                        <label htmlFor="remise">{t("achatItem.remise")}</label>
                        <InputNumber id="remise" value={item ? item.remise : 0} onChange={(e) => onInputNumerChange(e, 'remise')}/>
                    </div>
                    <div className="field col-6">
                        <label htmlFor="achat">{t("achatItem.achat")}</label>
                        <Dropdown  id="achatDropdown"  value={item ? item.achat : ''} options={achats} onChange={(e) => onDropdownChange(e, 'achat')}   placeholder="Sélectionnez un achat" filter filterPlaceholder="Rechercher un achat" optionLabel="reference" showClear />
                    </div>
                </div>
            </TabPanel>
        </TabView>
    </Dialog>
);
};
export default Edit;
